
```{r load_libraries}

library(GaRPackg)

library(tidyverse)

library(readxl)

library(zoo)

```

```{r set_params}

parameters_list = list()

parameters_list$horizon_list = c(4)

parameters_list$quantile_vec = c(0.1,0.25,0.5,0.75,0.9)
```

```{r import_data}

Raw_data <- read_excel(
  paste0(Sys.getenv("USERPROFILE"),
         "\\OneDrive - Bank Of Israel\\Data\\BoI",
         "\\var_data\\Data_for_Bootstrap.xlsx"),
  sheet = "Quarterly")

bootstrap_data = Raw_data  %>% 
  rename_all(tolower) %>% 
  mutate(date = as.yearqtr(date)) %>%
  mutate(across(-date, as.numeric))

bootstrap_data = bootstrap_data %>% 
 slice(84:nrow(.))


```

```{r get_all_combinations_test}

category_params_df = list(
  Market = list(
    optional = 
      c("term_spread",
        "us_gov_10y_rate",
        "us_gov_12m_rate",
        "eq_premium_q")
  ),
  Risk = list(
    optional = c(
      "dfy",
      "svar",
      "vix",
      "financial_uncertainty_index")
  ),
  Firm = list(
    optional = 
      c("pe_ratio",
        "div_yield",
        "book_to_market",
        "de")
  ),
  Macro =  list(
    optional = c(
      "infl_y",
      "output_gap",
      "unemployment_gap")
  )
) %>%
  enframe(name = "category", value = "params") %>%
  mutate(part_comb_df = map2(category, params,
                             function(temp_name, temp_part) {
                               temp_part_df = GaRPackg:::get_partition_combs(partitions_list = temp_part,partition_name = temp_name)
                             }))


feature_select_df = map(
  category_params_df$category,function(temp_cat){
    temp_df = category_params_df %>% 
      filter(category == temp_cat) %>% 
      select(part_comb_df) %>% 
      unnest(cols = c(part_comb_df))
    return(temp_df)
                        }
  ) %>% 
  reduce(full_join, by = character()) %>% 
  unite(col = name,starts_with("name"),sep = "-") %>% 
  mutate(temp_part = pmap(list(Market,Risk,Firm,Macro),c)) %>% 
  filter(!name == "Market-0-Risk-0-Firm-0-Macro-0") %>% 
  mutate(temp_part = map(temp_part, function(x){
    
    return(x[nchar(x) > 0])
    
  }))



```

```{r get_benchmark_model}

intercept_forecast = get_gar_forecast(
  partitions_list = NULL,
  vars_df = bootstrap_data,
  target_var_name = "eq_premium",
  horizon_list = parameters_list$horizon_list,
  quantile_vec = parameters_list$quantile_vec)

actual_df = bootstrap_data %>% 
  select(date, eq_premium) %>% 
  filter(complete.cases(.)) %>% 
  rename(actual_values = eq_premium)

```

```{r get_out_of_sample_fit}

fit_df = feature_select_df %>% 
  slice_sample(n = 2) %>% 
  mutate(ear_forecast = map(temp_part, function(part){

    names_vec = unlist(part,use.names = FALSE)
    
    temp_df = bootstrap_data %>% 
      select(date, eq_premium, all_of(names_vec))
    
    temp_win_len = temp_df %>% 
      filter(date <= as.yearqtr("2000 Q1")) %>%
      pull(date) %>% 
      length()
                              
   
    temp_forecast = get_gar_forecast(partitions_list = part,
                     vars_df = temp_df,
                     win_len = temp_win_len,
      target_var_name = "eq_premium",
      horizon_list = parameters_list$horizon_list,
      quantile_vec = parameters_list$quantile_vec)
    
    temp_intercept = get_gar_forecast(partitions_list = NULL,
                     vars_df = temp_df,
                     win_len = temp_win_len,
      target_var_name = "eq_premium",
      horizon_list = parameters_list$horizon_list,
      quantile_vec = parameters_list$quantile_vec)
    
    return(list(temp_forecast = temp_forecast,
                temp_intercept = temp_intercept))
    
  })) %>% 
  mutate(temp_forecast = map(ear_forecast,
                             ~.[["temp_forecast"]])) %>% 
  mutate(temp_intercept = map(ear_forecast,
                              ~.[["temp_intercept"]])) %>% 
  select(-ear_forecast)

# write_rds(fit_df,paste0("C:\\Users\\internet",
#                         "\\OneDrive - Bank Of Israel\\Data\\BoI",
#                         "\\var_data\\fit_df.rds"))

```

```{r calculate_pit_and_r2}

evaluation_metrics_df = fit_df %>% 
  select(name, temp_part, temp_forecast, temp_intercept) %>% 
  mutate(q2 = map2(temp_forecast, temp_intercept,
                   function(temp_forecast, temp_intercept){
    
    temp_q2 = quantile_r2_score(forecast_df = temp_forecast,
                                actual_df = actual_df,
                                benchmark_df = temp_intercept)
    return(temp_q2)
    
  })) %>% 
  mutate(pit = map(temp_forecast, function(temp_forecast){
    
    temp_pit = quantile_pit_score(forecast_df = temp_forecast,
                                actual_df = actual_df)
    return(temp_pit)
    
  }))

```

```{r dist_of_quantile_r2}

# evaluation_metrics_df %>% 
#   select(temp_part,q2) %>% 
#   unnest(q2) %>% 
#   write_csv(paste0("C:\\Users\\internet",
#                         "\\OneDrive - Bank Of Israel\\Data\\BoI",
#                         "\\var_data\\quantile_r2.csv"))
# 
# evaluation_metrics_df %>% 
#   select(temp_part,pit) %>% 
#   unnest(pit) %>% 
#   write_csv(paste0("C:\\Users\\internet",
#                         "\\OneDrive - Bank Of Israel\\Data\\BoI",
#                         "\\var_data\\pit.csv"))


evaluation_metrics_df %>% 
  select(temp_part,q2) %>% 
  unnest(q2) %>% 
  group_by(quantile) %>% 
  summarise(temp_list = list(tibble(probs = c(0.1,0.5,0.9),
                            r2 = quantile(quantile_r2,c(0.1,0.5,0.9)))),
            .groups = "drop") %>% 
  unnest(temp_list) %>% 
  pivot_wider(names_from = probs, values_from = r2,
              names_prefix = "q_") %>% 
  ggplot(aes(x = quantile)) + 
  geom_point(aes(y = q_0.5)) + 
  geom_errorbar(aes(ymin = q_0.1,ymax = q_0.9)) + 
  ylab(NULL)

```

```{r dist_of_pit}

evaluation_metrics_df %>% 
  select(temp_part,pit) %>% 
  unnest(pit) %>% 
  mutate(pit = pit - as.numeric(quantile)) %>% 
  group_by(quantile) %>% 
  summarise(temp_list = list(tibble(probs = c(0.1,0.5,0.9),
                            pit = quantile(pit,c(0.1,0.5,0.9)))),
            .groups = "drop") %>% 
  unnest(temp_list) %>% 
  pivot_wider(names_from = probs, values_from = pit,
              names_prefix = "q_") %>% 
  ggplot(aes(x = quantile)) + 
  geom_point(aes(y = q_0.5)) + 
  geom_errorbar(aes(ymin = q_0.1,ymax = q_0.9)) + 
  ylab(NULL) + ggtitle("Pit distribution")

```

