---
title: "Preliminary analysis"
output:
  html_document:
    toc: true
    toc_depth: 3
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE, echo = FALSE, message = FALSE,
  warning = FALSE, comment = "#>", fig.width = 10
)
```

```{r load_libraries}

library(GaRPackg)

library(tidyverse)

library(lubridate)

library(readxl)

library(zoo)

library(slider)

```


```{r set_params}

partitions_list_ear = list(
  Macro_Conditions = c("Infl_y", "Output_Gap"),
  Firm_Performance_indicatores = c("PE_Ratio", "Div_Yield"),
  Financial_uncertainty_index = c("Financial_uncertainty_index")) %>% 
  map(tolower)

target_var_name = "eq_premium"

horizon_list=c(1,4)

quantile_vec= c(0.10,0.25,0.5,0.75,0.90)

pca.align.list =  list(Macro_Conditions = list("infl_y", FALSE),
                       Firm_Performance_indicatores=list("div_yield",TRUE))

```


```{r import_data}

Raw_data <- read_excel(
  paste0(Sys.getenv("USERPROFILE"),
         "\\OneDrive - Bank Of Israel\\Data\\BoI",
         "\\var_data\\Data_for_R.xlsx"),
  sheet = "Quarterly")

ear_data = Raw_data  %>% 
  rename_all(tolower) %>% 
  select(date,eq_premium,
         unlist(partitions_list_ear, use.names = FALSE)) %>%
  mutate(date = as.yearqtr(date)) %>%
  mutate(across(-date, as.numeric)) %>%
  filter(complete.cases(.))



```



```{r plot_equity_premium]}

ear_data %>% 
  ggplot(aes(date, eq_premium)) + 
  geom_line() + 
  xlab(NULL) + ylab(NULL) + ggtitle("S&P500 equity premium (percent)")


```


# VaR Analysis

```{r run_analysis}

results = run_GaR_analysis(
  partitions_list = partitions_list_ear,
  vars_df = ear_data,
  target_var_name = target_var_name,
  horizon_list = horizon_list,
  quantile_vec = quantile_vec,
  preprocess_method = "pca",
  pca.align.list = pca.align.list,
  return_objects_list = TRUE
)


```

## Estimation results

### PCA


```{r pca_loadings}

results %>% 
  extract_pca_loadings_from_gar_model() %>% 
  ggplot(aes(x = coeff,
             y = tidytext::reorder_within(rowname,coeff,partition ))) + 
  geom_col(width = 0.5) + 
  tidytext::scale_y_reordered() + 
  facet_wrap(~partition, scales = "free") + 
  xlab(NULL) + ylab(NULL)



```


```{r pca_timeseries}

results %>% 
  extract_pca_timeseries_from_gar_model() %>% 
  pivot_longer(-date) %>% 
  ggplot(aes(date, value)) + 
  geom_line() + 
  facet_wrap(~name, scales = "free") + 
  xlab(NULL) + ylab(NULL)

```


### Quantile regression coefficients

```{r plot_coeffs}

results %>% 
  extract_coeffs_from_gar_model() %>% 
  filter(!partition == "Intercept") %>% 
  ggplot(aes(quantile, coeff)) + 
  geom_col(width = 0.5, aes(fill = significant)) + 
  scale_fill_viridis_d() + 
  geom_hline(yintercept = 0, linetype = "dashed") + 
  facet_grid(rows = vars(partition), cols = vars(horizon),
             scales = "free") + 
  xlab(NULL) + ylab(NULL) + 
  theme(legend.title = element_blank())
```


```{r plot_factor_contribution}

results %>% 
  extract_factor_contribution_from_gar_model(target_quantile = "0.5") %>% 
  filter(horizon == 4) %>% 
  select(-horizon) %>% 
  pivot_longer(-c(date)) %>% 
  ggplot() + 
  geom_col(aes(date, value, fill = name)) + 
  geom_line(data = results$fitted_df %>% 
              filter(horizon == 4) %>% 
              filter(quantile == 0.5), aes(x = date, y = fitted_values)) + 
  xlab(NULL) + ylab(NULL)

```



### In sample prediction

```{r plot_in_sample_forecast}

results %>% 
  pluck("fitted_df") %>% 
  ggplot() + 
  geom_line(data = . %>% 
              filter(horizon == 4 & quantile == 0.5),
            aes(date, fitted_values)) + 
  geom_ribbon(data = . %>% 
                filter(horizon == 4 & quantile %in% c(0.25,0.75)) %>% 
                pivot_wider(names_from = quantile,names_prefix = "q_",
                            values_from = "fitted_values"),
              aes(x = date, ymin = q_0.25, ymax = q_0.75, alpha = 0.5),
              show.legend = FALSE) + 
  xlab(NULL) + ylab(NULL) + 
  theme(legend.title = element_blank())



```



## Evaluation of out of sample

```{r out_of_sample_forecast}

# set window length so that OS forecasts start at year 2000

win_len = (ear_data %>% 
  filter(lubridate::year(date) >= 2000) %>% 
  nrow()) - max(horizon_list) + 1

out_of_sample_forecast = get_gar_forecast(
  partitions_list = partitions_list_ear,
  vars_df = ear_data,
  target_var_name = "eq_premium",
  horizon_list = horizon_list,
  quantile_vec = quantile_vec,
  pca.align.list = pca.align.list,
  win_len = win_len)

out_of_sample_intercept = get_gar_forecast(
  partitions_list = NULL,
  vars_df = ear_data,
  target_var_name = "eq_premium",
  horizon_list = horizon_list,
  quantile_vec = quantile_vec,
  pca.align.list = pca.align.list,
  win_len = win_len)

```


```{r plot_out_of_sample_forecasts}

out_of_sample_forecast %>% 
  filter(horizon == 4) %>% 
  ggplot(aes(date, forecast_values, color = quantile)) + 
  geom_line()

```

```{r make_deciles_df}

deciles_df = Raw_data %>% 
  rename_all(tolower) %>% 
  select(date, eq_premium) %>% 
  mutate(date = ymd(date)) %>% 
  filter(date >= as_date("1960-09-30") & date <= as_date("2021-12-31")) %>% 
  mutate(eq_premium = as.numeric(eq_premium)) %>% 
  mutate(q_0.25 = slide_dbl(eq_premium,.f = ~quantile(.,0.25),
                         .before = Inf)) %>% 
  mutate(q_0.75 = slide_dbl(eq_premium,.f = ~quantile(.,0.75),
                         .before = Inf))

```

```{r compare_deciles_df}

deciles_df %>% 
  select(-eq_premium) %>% 
  mutate(date = as.yearqtr(date)) %>% 
  pivot_longer(-date,names_to = "quantile",
               values_to = "BoI_values") %>% 
  mutate(quantile = str_remove(quantile, "q_")) %>% 
  inner_join(out_of_sample_forecast %>% 
               filter(horizon == 4) %>% 
               select(-horizon) %>% 
               rename(EaR_values = forecast_values),
             by = c("quantile","date")) %>% 
  inner_join(out_of_sample_intercept %>% 
               filter(horizon == 4) %>% 
               select(-horizon) %>% 
               rename(EaR_intercept = forecast_values),
             by = c("quantile","date")) %>% 
  pivot_longer(-c(date, quantile)) %>% 
  ggplot(aes(date, value, color = quantile, linetype = name)) +
  geom_line(lwd = 1) + 
  xlab(NULL) + ylab(NULL) + 
  ggtitle("Comparison between BoI (market division) and EaR forecasts") + 
  theme(legend.title = element_blank())

```

