---
title: "Out of sample forecasting"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Out of sample forecasting}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, }
library(GaRPackg)
library(tidyverse)
library(zoo)
```

In this vignette we'll look an the out of sample forecasting functions.
The forecasting is performed by rolling window method with expanding window by
default.

We start by defining minimal setup for forecasting

```{r import_process_data}

data("gar_data")

gar_data = gar_data %>% 
  select("date", "gdp","ind_prod_israel","credit","house_price")  %>%
  mutate(date = as.yearqtr(date)) 

partitions_list = list(
  macro = c("gdp_yoy", "ind_prod_israel_yoy"),
  fin = c("credit_yoy", "house_price_yoy")
)

df = gar_data %>%
  preprocess_df(vars_to_yoy = c("gdp","ind_prod_israel","credit","house_price"))



```


```{r run_forecast}

forecast_df = get_gar_forecast(partitions_list = partitions_list,
                               vars_df = df,
                               target_var_name = "gdp_yoy",
                               horizon_list = c(1,12),
                               quantile_vec = c(0.05,0.25,0.5,0.75,0.95))

```


```{r plot_fan_chart, fig.width=6}

plot_fan_chart(forecast_df = forecast_df,
               actual_df = df %>% 
                 select(date, gdp_yoy) %>% 
                 rename(actual_values = gdp_yoy),
               fan_chart_date = max(df$date))

```

