---
title: "Feature selection"
fontsize: 11pt
output:
  rmarkdown::pdf_document:
    latex_engine: xelatex
    number_sections: true
    includes:
            in_header: Preamble.tex

vignette: >
  %\VignetteIndexEntry{GaR analysis}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF_8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE, echo = FALSE, message = FALSE,warning = FALSE,
  comment = "#>"
)
```


```{r setup}

devtools::load_all()

setwd(paste0(file.path(Sys.getenv("USERPROFILE"),fsep = "\\"),
             "\\Documents\\GaRPackg\\vignettes"))


```


```{r load_libraries}

library(cowplot)

library(gghighlight)

library(tidyselect)

library(tidyverse)

library(quantreg)

library(corrplot)

library(stargazer)

library(xtable)

```


```{r import_data, child="GaR-ImportAndProcessData.Rmd"}

```


```{r Set_partitions, child="Partition-Specs.Rmd"}

# source("Partition-Specs.R",echo = FALSE)

current_partitions_list = partitions_list[!names(partitions_list) %in%
                                            "extensive"]


```


```{r make_actual_gdp_df}

actual_gdp_df = df %>% 
  select(Date, GDP) %>% 
  filter(complete.cases(.)) %>% 
  rename(GDP_actual = GDP) %>% 
  mutate(Forecast_Period = paste(Date - 1, Date, sep = "-")) %>% 
  select(-Date) %>% 
  select(Forecast_Period, GDP_actual)

```


```{r GaR_analysis}

results_list = lapply(current_partitions_list,
                      function(temp_partition){
                        temp_res = run.GaR.analysis(
                          partitions_list = temp_partition,
                          vars_df = df,
                          horizon_list = parameters_list$horizon_list,
                          quantile_vec = parameters_list$quantile_vec,
                          pca.align.list = list(Dom_FCI = list(
                            var_name = "Spread_CPI_corp",
                            positive_direction = FALSE)),
                          run_ols_reg = FALSE)
                       
                        return(temp_res) 
                        
                      })

results_list$intercept = run.GaR.analysis(partitions_list = NULL,
                   vars_df = df,
                   horizon_list = parameters_list$horizon_list,
                   quantile_vec = parameters_list$quantile_vec,
                   pca.align.list = list(Dom_FCI = list(
                     var_name = "Spread_CPI_corp",
                     positive_direction = FALSE)))


```


```{r Forecast}

forecasts = lapply(results_list, get.gar.forecast,
                   win_len = 30, quantile_vec = parameters_list$quantile_vec,
                   out_of_sample_step = 0)

forecast_df = map(names(forecasts), ~ forecasts[[.x]] %>% 
                    mutate(Partition = .x)) %>% 
  bind_rows() %>% 
  filter(Forecast_Status == "Out of Sample") %>% 
  select(-Forecast_Status) %>% 
  pivot_wider(id_cols = c(Date,Quantile,Horizon),
              names_from = "Partition", values_from = "GaR_forecast")

forecast_df = forecast_df %>% 
  mutate(Forecast_Period = paste(
    Date + as.numeric(Horizon) * 0.25 - 1,
    Date + as.numeric(Horizon) * 0.25,
    sep = "-")) %>% 
  inner_join(actual_gdp_df, by = "Forecast_Period") %>% 
  select(-Date, -Forecast_Period) %>% 
  filter(complete.cases(.))


```


```{r R2_scores} 

r2_scores = forecast_df %>% 
  group_by(Quantile, Horizon) %>% 
  summarise(across(c(-intercept, -GDP_actual), ~quantile.r2.score(
    realized_estimates = GDP_actual,
    forecast_values = .x,
    quantile = as.numeric(Quantile[1]),
    benchmark_values = intercept)),.groups = "drop")




```


```{r plot_res}

temp = r2_scores %>% 
  select(-Horizon) %>% 
  mutate(Weight = abs(as.numeric(Quantile) - 0.5) * 2) %>% 
  select(-Quantile) %>% 
  summarise(across(starts_with("basic"), ~weighted.mean(.x,Weight))) %>% 
  pivot_longer(cols = everything(),names_to = "model", values_to = "avg_score") %>% 
  arrange(-avg_score)

ggplot(temp, aes(x = reorder(model, avg_score), y = avg_score)) + 
  geom_col(width = 0.5) + 
  labs(x = "", y = "", title = "Partition comparison according to weighted average") + 
  coord_flip() + 
  theme_bw()

```

