
```{r import_libraries}

library(tsibble)

library(forecast)

library(fpp3)


```


```{r import_cpi}

cpi = read_csv(paste0("C:\\Users\\Misha\\OneDrive - Bank Of",
                      " Israel\\Data\\BoI\\BOI_CPI.csv"),
               skip = 15, col_names = c("date","CPI")) %>% 
  mutate(date = as.yearqtr(date, format = "%d/%m/%Y")) %>% 
  filter(date >= min(raw_df$date)) %>% 
  group_by(date) %>% 
  summarise(Avg_CPI = mean(CPI, na.rm = TRUE)) %>% 
  ungroup()

```



```{r make_tsibble}

temp_df = list(raw_df %>%
                 select(date, credit),
               cpi) %>% 
  reduce(full_join, by = "date")

temp_df = temp_df %>% 
  mutate(credit_real = credit / Avg_CPI * 
           Avg_CPI[date == "2000 Q1"])

temp_df = temp_df %>%
  as_tsibble(index = date)


```


```{r}

ggplot(temp_df %>% 
  pivot_longer(cols = c(credit, credit_real),
               names_to = "Category", values_to = "Val"),
  aes(x = date, y = Val, color = Category)) + 
  geom_line() + 
  theme_bw() + 
  theme(legend.position = "bottom")

```



