
```{r load_desc_libraries}

library(corrplot)

library(stargazer)

```


```{r correlations, eval=FALSE}

cor_mat = df %>% 
  select(-starts_with("staff")) %>% 
  select(-starts_with("dsge")) %>% 
  select(-date) %>% 
  select(-any_of(c("interbank_spread","ils_usd_spread_pct"))) %>% 
  filter(complete.cases(.)) %>% 
  cor()


corrplot::corrplot(cor_mat,order = "hclust",addrect = 5)

```


```{r descriptive_plots, eval=FALSE}


plot_list = lapply(names(current_partition), function(temp_name){
  
  temp_df = df %>% 
    select(date, unlist(current_partition[[temp_name]])) %>% 
    gather(key = Feature, value = Val,-date) %>% 
    mutate(Type = if_else(Feature %in% parameters_list$vars_to_rates,
                          "Rate","Level"))
  
  temp_plot = ggplot(temp_df,aes(x = date, y = Val, color = Feature)) + 
    geom_line() + 
    labs(x = "", y = "", title = temp_name) + 
    facet_wrap(~Type, scales = "free") + 
    theme_bw() + 
    theme(legend.position = "bottom",
        legend.title = element_blank(),
        plot.title = element_text(hjust = 0.5))
  
  print(temp_plot)
  
})

names(plot_list) = names(current_partition)


  
```


```{r descriptive_table, results='asis'}

df %>% 
  select(date, unlist(current_partition, use.names = FALSE)) %>% 
  as.data.frame() %>% 
  stargazer(summary = TRUE, header = FALSE)
  


```

