---
title: "GaR analysis"
fontsize: 11pt
output:
  rmarkdown::pdf_document:
    latex_engine: xelatex
    number_sections: true
    includes:
            in_header: C:\\Users\\internet\\Documents\\GaRpckg\\vignettes\\Preamble.tex

vignette: >
  %\VignetteIndexEntry{GaR analysis}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF_8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE, echo = FALSE, message = FALSE,warning = FALSE,
  comment = "#>"
)
```


```{r setup}

devtools::load_all()

library(GaRPackg)

# setwd("C:\\Users\\Misha\\Documents\\GaRPackg\\vignettes")
```


```{r load_libraries}

library(cowplot)

library(gghighlight)

library(tidyselect)

library(tidyverse)

library(quantreg)

library(rlang)

```


```{r Import_data}

raw_data = list(osnat_list = import.osnat.data(),
                michael_list = import.michael.data())

raw_data$raw_df = full_join(raw_data$osnat_list$osnat_df,
                            raw_data$michael_list$michael_df,
                            by = "Date") %>% 
  arrange(Date)

```


```{r Set_parameters}

setwd("C:\\Users\\internet\\Documents\\GaRpckg\\vignettes")

partitions_list = list()

parameters_list = list()

data_list = list()

parameters_list$quantile_vec = c(0.05,0.25,0.5,0.75,0.95)

parameters_list$horizon_list = list(1,8,12)

parameters_list$drop_series = c("Vacancies_Rate","Telbor_1Y","STARTUP_FP",
                "Term_spread","Sovereigh_spread",
                "Interbank_spread","LT_real_rate_change",
                "TA125_Close","Indus_prod_ind","ILS_EURO",
                "breakeven_inflation_5_10_fwd")

parameters_list$forecast_win_len = 30

parameters_list$forecast_step = 1


```


```{r Set_partitons-extensive}

partitions_list$extensive = list(Dom_Real = list("GDP_F","Ind_Prod_Israel",
                                  "C_FP","G_NDEFIMP_FP","INV_FP",
                                  "INV_NI_FP","EXP_ND_FP","IMP_ND_FP",
                                  "STARTUP_FP"),
                  Dom_Prices = list("CPI","breakeven_inflation_1Y",
                                    "breakeven_inflation_2_3_fwd",
                                    "breakeven_inflation_5_10_fwd",
                                    "CPI_season_adj",
                                    "CPI_no_house_fruits_season_adj",
                                    "CPI_no_house_season_adj",
                                    "CPI_no_house","CPI_no_fruits"),
                  Rates = list("BOI_rate","Telbor_1Y","real_rate_1",
                               "real_rate_2_3_fwd","real_rate_5_10_fwd"),
                  External = list("CA","ILS_USD","ILS_EURO",
                                  "ILS_Yen","ILS_GBP"),
                  Global = list("VIX","Ind_Prod_advanced",
                                "Brent","Commodity_Non_Energy",
                                "gdp_us","gdp_euro","gdp_japan",
                                "gdp_uk","infl_us","infl_euro",
                                "infl_japan","infl_uk","rate_euro","rate_us",
                                "rate_uk","rate_japan","US_10","EU_10",
                                "UK_10","JPN_10", "US_5","EU_5","UK_5","JPN_5",
                                "IMP_OECD"),
                  Labor = list("Wage","EMP","Unemp_rate","Vacancies_Rate"),
                  National_Security = list("Tourists"),
                  Spread = list("Spread_CPI_corp",
                                "ILS_USD_spread_pct","Interbank_spread",
                                "Sovereigh_spread",
                                "Term_spread"),
                  Volatility = list("ILS_USD_impl_vol","TA_35_impl_vol"),
                  Returns = list("TA125_Close"),
                  Credit = list("Credit_to_non_fin_sector",
                                "Avg_House_Price_index"))

```


```{r Set_partitions-basic}

partitions_list$basic = list(Dom_Real = list("GDP_F","Ind_Prod_Israel",
                                             "CPI","BOI_rate","real_rate_1"),
                             Global_Real = list("CA","ILS_USD","gdp_us",
                                                "gdp_euro","infl_us","infl_euro",
                                                "Ind_Prod_advanced","rate_euro","rate_us"),
                             Dom_Fin =  list("Spread_CPI_corp",
                                "ILS_USD_spread_pct","Interbank_spread",
                                "Sovereigh_spread", "Term_spread",
                                "ILS_USD_impl_vol","TA_35_impl_vol"),
                             Credit = list("Credit_to_non_fin_sector",
                                "Avg_House_Price_index","TA125_Close"),
                             Global_Fin = list("VIX"))


```


```{r Process_data}

vars_to_rates = c("Ind_Prod_advanced","Ind_Prod_Israel",
                  "GDP_F","C_FP","G_NDEFIMP_FP","INV_FP",
                  "INV_NI_FP","EXP_ND_FP","IMP_ND_FP","STARTUP_FP",
                  "CPI_season_adj","CPI_no_house_fruits_season_adj",
                  "CPI_no_house_season_adj","CPI", "CPI_no_house",
                  "CPI_no_fruits","ILS_USD","ILS_EURO","ILS_Yen","ILS_GBP",
                  "gdp_us","gdp_euro","gdp_japan","gdp_uk",
                  "Brent","Commodity_Non_Energy","Labor_pop",
                  "Wage","EMP","Labor_force","Tourists","TA125_Close",
                  "Avg_House_Price_index","Credit_to_non_fin_sector",
                  "IMP_OECD")

df = raw_data$raw_df %>% 
  select(-GDP_F, -GDP_no_tax,-GDP_season_adj) %>% 
  rename(GDP_F = GDP_no_startup)


# Normalize CA by GDP

df = df %>% 
  mutate(CA = CA / GDP_F)


# Transform variables to rates of change YoY

df = df %>% 
  mutate_at(vars(vars_to_rates),
            .funs = list(~./lag(.,4)-1))


# Calculate difference

df = df %>%
  mutate(real_rate_2_3_fwd = real_rate_2_3_fwd - real_rate_5_10_fwd) %>%
  mutate(BOI_rate = BOI_rate - real_rate_5_10_fwd) %>%
  mutate(US_5 = US_5 - US_10) %>%
  mutate(EU_5 = EU_5 - EU_10) %>%
  mutate(JPN_5 = JPN_5 - JPN_10) %>%
  mutate(Ger_5 = Ger_5 - Ger_10) %>%
  mutate(UK_5 = UK_5 - UK_10) %>%
  mutate(rate_us = rate_us - US_10) %>%
  mutate(rate_euro = rate_euro - EU_10) %>%
  mutate(rate_japan = rate_japan - JPN_10) %>%
  mutate(rate_uk = rate_uk - UK_10) %>%
  select(-ends_with("10"))

```


```{r make_data_list}

data_list$complete_cases_df = df %>%
  filter(complete.cases(.))

data_list$long_series_df = df %>% 
  select(-!!(parameters_list$drop_series))


data_list$interpolated_df = df %>%
  mutate_at(.vars = vars(-Date), interpolate)



```


```{r run_partitions_robustness}

results_list = lapply(partitions_list, function(temp_part){
  
  temp_result = run.GaR.analysis(partitions_list = temp_part,
                                 vars_df = data_list$long_series_df,
                                 horizon_list = parameters_list$horizon_list,
                                 quantile_vec = parameters_list$quantile_vec)
  
  
})

```


```{r get_partitions_forecasts}

forecast_list = lapply(results_list, function(temp_result){
  
  temp_forecast = get.gar.forecast(gar_obj = temp_result,
                                   win_len = parameters_list$forecast_win_len,
                                   quantile_vec = parameters_list$quantile_vec,
                                   out_of_sample_step = parameters_list$forecast_step)
  
  
})

```



```{r compare_partitions_forecast}

forecast_df = lapply(names(forecast_list), function(temp_name){
  
  temp_df = forecast_list[[temp_name]] %>% 
    filter(complete.cases(.)) %>% 
    mutate(Partition = temp_name)
  
  
}) %>% 
  rbind_all() %>% 
  mutate(Date = as.yearqtr(Date))


accuracy_df = forecast_df %>% 
  group_by(Partition, Horizon, Quantile, Forecast_Status) %>% 
  summarise(RMSE = sqrt(mean(Error ^ 2)),MAD = mean(abs(Error))) %>% 
  ungroup() %>% 
  mutate(Horizon = factor(Horizon, levels = c("1","8","12")))




```


```{r plot_RMSE}

in_sample_plot = ggplot(accuracy_df %>% 
                          filter(Forecast_Status == "In Sample"),
                        aes(x = Partition, y = RMSE)) + 
  geom_col() + 
  labs(x = "", y = "", title = "In sample") +
  facet_wrap(~Horizon) + 
  theme_bw() + 
  theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

out_sample_plot = ggplot(accuracy_df %>% 
         filter(Forecast_Status == "Out of Sample"), aes(x = Partition, y = RMSE)) + 
  geom_col() + 
  labs(x = "", y = "", title = "Out of sample") + 
  facet_wrap(~Horizon) + 
  theme_bw() + 
  theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

plot_title = ggdraw() + 
  draw_label("Root Mean Square Error")

plot_row = plot_grid(in_sample_plot, out_sample_plot)

plot_grid(plot_title, plot_row,nrow = 2,rel_heights = c(0.1,1))


```



```{r plot_MAD}

in_sample_plot = ggplot(accuracy_df %>% 
                          filter(Forecast_Status == "In Sample"),
                        aes(x = Partition, y = MAD)) + 
  geom_col() + 
  labs(x = "", y = "", title = "In sample") +
  facet_wrap(~Horizon) + 
  theme_bw() + 
  theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

out_sample_plot = ggplot(accuracy_df %>% 
         filter(Forecast_Status == "Out of Sample"), aes(x = Partition, y = RMSE)) + 
  geom_col() + 
  labs(x = "", y = "", title = "Out of sample") + 
  facet_wrap(~Horizon) + 
  theme_bw() + 
  theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

plot_title = ggdraw() + 
  draw_label("Mean Absolute Deviation")

plot_row = plot_grid(in_sample_plot, out_sample_plot)

plot_grid(plot_title, plot_row,nrow = 2,rel_heights = c(0.1,1))


```

