

```{r get_predict_df}

prediction_df = map_dfr(names(results$qreg_result),
                        function(temp_name){
  
  temp_predict = predict(results$qreg_result[[temp_name]],
                         newdata = results$reg_df) %>% 
    as.data.frame() %>% 
    cbind(date = results$reg_df$date, horizon = temp_name) %>% 
    rename_all(~str_remove_all(.,"tau= ")) %>% 
    pivot_longer(-c("date", "horizon"), names_to = "quantile")
  
  
  
})

```


```{r plot_gar_timeseries}

prediction_df %>% 
  filter(quantile == "0.05") %>% 
  ggplot(aes(x = date, y = value, color = horizon)) + 
  geom_line() + 
  scale_x_yearqtr() + 
  labs(title = "GaR (5% quantile) timeseries at different horizons",
       x = "", y = "") + 
  theme_bw() + 
  theme(legend.position = "bottom", plot.title = element_text(hjust = 0.5))

```


```{r plot_historical_events}

recessions = read.csv(paste0(
  file.path(Sys.getenv("USERPROFILE"),fsep="\\"),
  "\\OneDrive - Bank Of Israel\\",
  "Data\\BoI\\GaR_Data","\\recessions.csv")) %>%
  mutate(across(c(Start, End), ~as.yearqtr(.)))

events = read.csv(paste0(
  file.path(Sys.getenv("USERPROFILE"),fsep="\\"),
  "\\OneDrive - Bank Of Israel\\",
  "Data\\BoI\\GaR_Data","\\events.csv")) %>%
  mutate(across(c(Start, End), ~as.yearqtr(.)))


temp_df = prediction_df %>% 
              filter(quantile == "0.05") %>% 
              filter(horizon %in% c(1,12))


ggplot() +
  ylim(c(-0.12,0.08)) +
  geom_point(data = temp_df,
             mapping = aes(x = date, y = value, color = horizon)) +
  geom_line(data = temp_df,
            mapping = aes(x = date, y = value, color = horizon)) +
  geom_rect(data = recessions,
            mapping = aes(xmin = Start, xmax = End,
                          ymin = -Inf, ymax = Inf),
            fill = "lightblue", alpha = 0.5) +
  xlab(NULL) + ylab(NULL) + 
  theme_bw() +
  theme(legend.position = "bottom") +
  geom_point(data = temp_df %>%
             filter(date %in% events$Start),
           mapping = aes(x = date, y = value),
           color = "blue") +
  geom_segment(data = temp_df %>%
                 filter(date %in% events$Start) %>%
                 group_by(date) %>% 
                 summarise(value = min(value), .groups = "drop"),
             mapping = aes(x = date, y = c(0.0745,0.0745,0.0545),
                           xend = date, yend = value),
            arrow = arrow(length = unit(0.1,"cm")),
             color = "blue") +
  geom_text(data = events,
            mapping = aes(x = Start + 1, y = c(0.08,0.08,0.06),
                                          label = Event),
            color = "blue")

rm(temp_df)

```



```{r plot_gar_bounds_timeseries, fig.height=10, eval=FALSE}

ggplot(prediction_df %>% 
  filter(quantile %in% c("0.05","0.5","0.95")),
       aes(x = date, y = value, color = quantile)) + 
  geom_line() + 
  scale_x_yearqtr() + 
  labs(title = "GaR normalized upper and lower quantile timeseries",
       x = "", y = "") + 
  facet_wrap(~horizon,ncol = 1) + 
  theme_bw() + 
  theme(legend.position = "bottom", plot.title = element_text(hjust = 0.5))

```


```{r fan_chart}

gdp_df = df %>% 
  select(date, gdp) %>% 
  filter(complete.cases(.)) %>% 
  filter(date >= as.yearqtr("2018 Q1"))

fan_chart_df  = prediction_df %>% 
  filter(date == max(date))%>% 
  rename(Horizon = horizon, Quantile = quantile) %>% 
  fix_quantile_crossing() %>% 
  rename_all(tolower) %>% 
  pivot_wider(names_from = quantile,values_from = value) %>% 
  rename_at(vars(-date,-horizon),
            .funs = list(~paste0("Q_",.))) %>% 
  mutate(date = date + as.numeric(as.character(horizon)) * 0.25)
  
 

temp = fan_chart_df[nrow(fan_chart_df),]
temp$date = gdp_df$date[nrow(gdp_df)]
temp[,-1] = gdp_df$gdp[nrow(gdp_df)]

fan_chart_df = fan_chart_df %>% 
  rbind.data.frame(temp)

ggplot() +
  geom_line(data = gdp_df,
            aes(x = date, y = gdp)) +
  geom_ribbon(data = fan_chart_df,
              aes(x = date, ymin = Q_0.05, ymax = Q_0.95),
              fill = "lightblue",
              alpha = 0.6) +
   geom_ribbon(data = fan_chart_df,
               aes(x = date, ymin = Q_0.25, ymax = Q_0.75),
              fill = "lightblue",
              alpha = 0.5) +
  geom_line(data = fan_chart_df,
            aes(x = date, y = Q_0.50), color = "white") +
  labs(x = "", y = "",title = "Fan chart for gdp YoY growth rate") +
  scale_y_continuous(labels = scales::percent_format(accuracy = 0.5)) +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5))

rm(temp, gdp_df)

```


```{r factor_decomposition}

factor_df = extract_factor_contribution_from_gar_model(results) %>% 
  mutate(horizon = factor(horizon, levels = c(1,4,8,12)))


ggplot(data = factor_df %>% 
         mutate(Total = rowSums(across(-c("date","horizon")))) %>% 
         pivot_longer(-c("date","horizon")) %>% 
         filter(!name == "Total"),
       aes(x = date, y = value, fill = name)) + 
  geom_col(position = "stack") + 
  geom_line(data = factor_df %>% 
              mutate(Total = rowSums(across(-c("date","horizon")))) %>% 
              pivot_longer(-c("date","horizon")) %>% 
              filter(name == "Total") %>% 
              select(-name),inherit.aes = FALSE,aes(x = date, y = value)) + 
  scale_fill_viridis_d(option = "plasma") + 
  xlab(NULL) + ylab(NULL) + 
  facet_wrap(~horizon, scales = "free_y")


```


```{r quartile_skewness_plot}

results %>% 
  calculate_skew_and_iqr() %>% 
  filter(Horizon == 1) %>% 
  ggplot(aes(x = date, y = Skew)) + 
  geom_line() + 
  geom_hline(yintercept = c(-0.5,0.5),
             linetype = "dashed", color = "blue") + 
  xlab(NULL) + ylab(NULL) + ggtitle("Quartile skewness (1Q ahead)")



```

