
```{r set_plot_parameters}


names_table = tribble(
  
  ~old_name, ~new_name,
  "Dom_Macro","Dom. Macro",
  "Dom_Fin","Dom. Fin. Cond",
  "Dom_Fin_Cycle","Dom. Fin. Cycle",
  "Ext_Macro","Ext. Macro",
  "Ext_Fin","Ext. Fin. Cond",
)

# plot_names = c("Dom. Macro","Dom. Fin. Cond",
#                "Ext. Macro","Ext. Fin. Cond",
#                "Dom. Fin. Cycle")

my_fig_height = 8

theme_set(theme_bw() + theme(
  legend.position = "bottom",
  legend.title = element_blank()))

```


```{r set_pca_list}

pca_list = results$pca_obj

pca_list = pca_list[names_table$old_name]

pca_variance = map_dfr(names(pca_list), function(temp_name){

  data.frame(Name = temp_name,
             Variance = round(pca_list[[temp_name]]$pca$sdev[1] ^ 2 /
                                sum(pca_list[[temp_name]]$pca$sdev ^ 2),3),
             stringsAsFactors = FALSE)

})

```


```{r plot_pca_variance}

pca_variance %>% 
  ggplot(aes(x = reorder(Name, Variance), y = Variance)) + 
  geom_col() +
  xlab(NULL) + ylab(NULL) + ggtitle("First PCA explained variance") + 
  coord_flip()


```


```{r plot_pca_loadings, fig.width = 10, fig.height=my_fig_height}

pca_plots = map(names(pca_list), function(name){

  pca_var = round(pca_variance$Variance[
    pca_variance$Name == name] * 100,0)

  bar_plot = ggplot(data.frame(Name = names(pca_list[[name]]$pca$rotation[,1]),
                  Val = pca_list[[name]]$pca$rotation[,1]),
       aes(x = reorder(Name, Val), y = Val)) +
  geom_bar(stat = "identity", width = 0.5) +
  labs(x = "", y = "",
       title = paste0(names_table %>%
                        filter(old_name==name) %>%
                        pluck("new_name"), " (" ,pca_var, "%)")) +
  coord_flip() +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5))
  
  rm(pca_var)
  
  return(bar_plot)
  

})

plot_grid(plotlist = pca_plots, ncol = 2)

```


```{r plot_partiton_timeseries, fig.width = 10, fig.height=my_fig_height}


pca_timeseries_plots = lapply(names(pca_list), function(name){
  
  ggplot(data.frame(x = pca_list[[name]]$time_index,
                  y = pca_list[[name]]$pca$x[,1]), aes(x = x, y = y)) + 
    geom_line() + 
    labs(title = names_table %>%
                        filter(old_name==name) %>%
                        pluck("new_name"), x = "", y = "") + 
    scale_x_yearqtr() + 
    theme_bw() + 
    theme(plot.title = element_text(hjust = 0.5))

  })


plot_grid(plotlist = pca_timeseries_plots,ncol = 2)

```

