

```{r Set_import_parameters}

parameters_list = list()

parameters_list$quantile_vec = c(0.05, 0.25, 0.5, 0.75, 0.95)

parameters_list$horizon_list = list(1, 4, 8, 12)

parameters_list$drop_series = c(
  "vacancies_rate",
  "telbor_1Y",
  "STARTUP_FP",
  "sovereigh_spread",
  "interbank_spread",
  "lt_real_rate_change",
  "indus_prod_ind",
  "ils_euro",
  "breakeven_inflation_5_10_fwd"
)

parameters_list$vars_to_yoy = c(
  "ind_prod_us",
  "ind_prod_euro",
  "Ind_Prod_Israel",
  "gdp",
  "private_consumption",
  "public_consumption",
  "investment",
  "exports",
  "imports",
  "dom_gdp",
  "credit",
  "ta125_close",
  "house_price",
  "sp500",
  "dxy",
  "eurostoxx600",
  "state_of_economy_ind",
  "oecd_imp",
  "oil_p",
  "non_energy_p"
)

parameters_list$vars_to_diff = c(
  "boi_rate",
  "rate_us",
  "rate_euro",
  "unemployment"
  )


parameters_list$vars_to_4_ma = c(
  "gdp_us",
  "gdp_euro"
  )


```


```{r Import_data}

raw_df = import.from.fame.template(
  paste0(file.path(Sys.getenv("USERPROFILE"),fsep="\\"),
         "\\OneDrive - Bank Of Israel\\",
         "Data\\BoI\\GaR_Data\\Working_data",
         "\\data_fame.csv")) %>% 
  rename_all(tolower)




```


```{r Process_data}

df = raw_df %>% 
  mutate(dom_gdp = private_consumption + 
           public_consumption + investment) %>% 
  mutate(across(any_of(parameters_list$vars_to_yoy),
                calculate.YoY.returns)) %>% 
  mutate(across(any_of(parameters_list$vars_to_4_ma),
                ~ calculate.four.quarters.ma(.) * 4 / 100)) %>% 
  mutate(across(any_of(parameters_list$vars_to_diff),
                ~c(NA,diff(.))))


```


```{r set_current_partition}

current_partition = partitions_list$gdp_components


```


```{r df_filters}

df = df %>% 
  filter(across(unlist(current_partition, use.names = FALSE), ~!is.na(.))) %>%
  filter(date <= as.yearqtr("2019 Q4")) %>%
  identity()


```


```{r fill_last_NA, eval=FALSE}

df = df %>% 
  mutate_at(vars(gdp,credit),.funs = list(~fill.na.average(.)))

```

