---
title: "Growth at Risk: The Distribution of Future GDP Growth in Israel"
author: "Michael Gurkov and Osnat Zohar"
institute: "Bank of Israel \\newline Research Department"
date: "14 September, 2020"
classoption: t
output:
  beamer_presentation:
    includes:
      in_header: !expr here::here('vignettes/GaR-PresentationPreamble.tex')
    latex_engine: xelatex
    slide_level: 2
bibliography: "GaR.bib"
---


```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE, echo = FALSE, message = FALSE,
  warning = FALSE, comment = "#>"
)
```


## Motivation

\begin {itemize}
\itemsep3em
	\item
	Assessing risks to future economic activity is essential for making knowledgeable forecasts.
	\item
	An important factor: financial vulnerabilities.
	\item
	We provide a methodological tool for assessing risks to growth in Israel using real and financial variables:

	\vspace{1em}

\begin{center}
\begin{block}{}

	Given current macro-financial conditions, what is the distribution of
	expected economic growth?
	
\end{block}
\end{center}

\end{itemize}


## The Growth at Risk (GaR) Approach

\vspace{1em}

* GaR is a linear model of density forecasts
  + Based on quantile regression
  + Parsimonious
  + Easy to interpret

\vspace{1em}

* Proposed by @Adrian2019, operationalized by the IMF [@Prasad2019].

\vspace{1em}

* Applied to:
  + Advanced economies [@Aikman2018;@Alessandri2019]
  + Developing economies [@Komatsuzaki2019; @Bespalova2019]


# References {.unlisted .unnumbered}
## References {.allowframebreaks}

<div id="refs"></div>
