---
title: "GaR analysis"
output:
  rmarkdown::pdf_document:
    latex_engine: xelatex
    number_sections: true
    includes:
            in_header: C:\\Users\\Misha\\Documents\GaR\\GaR-preamble.tex

vignette: >
  %\VignetteIndexEntry{GaR analysis}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF_8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE, echo = FALSE, message = FALSE,warning = FALSE,
  comment = "#>"
)
```


```{r setup}

devtools::load_all()

library(GaRPackg)
```


```{r load_libraries}

library(zoo)

library(tidyselect)

library(ggplot2)

library(cowplot)

library(mFilter)

library(quantreg)

library(rlang)

```


```{r Set_parameters}

partitions = list(domestic_macro = list('real_gdp_yoy', 'industrial_prod_yoy',
                                        'pmi',"cyclical_composite_yoy"),
                  domestic_fci = list('term_spread', 'corporate_spread',
                                      'interbank_spread','sovereign_spread',
                                      'securities_ba_spread',
                                      'equity_returns_qoq', 'policy_rate',
                                      'cpi_inflation', 
                                      'implied_yield_cpi_bond_yoy',
                                      'inflation_expectations',
                                      'fx_returns_qoq', 'fx_ba_spread',
                                      'equity_implied_vol'),
                  leverage = list('private_credit_gdp', 'loan_deposits_ratio',
                                  'tier1_rwa', 'npl_ratio', 'share_fx_loans',
                                  'nfc_debt_equity',
                                  'derivatives_assets_capital',
                                  'liquid_assets_st_liabilities',
                                  'net_fx_positions_capital'),
                  external = list('reer_yoy', 'ca_gdp', 'trade_gdp',
                                  'dom_investment_gdp'),
                  world_macro = list('world_real_gdp_yoy',
                                     'world_indus_prod_yoy'),
                  world_fci = list('vix', 'nasdaq_vol', 'nasdaq_returns_qoq',
                                   'oil_future_qoq','us_reer_eme_yoy'))

```


```{r Import_data}

df = read.csv(paste0("C:\\Users\\Misha\\Documents\\GaR Python\\Israel",
                     " GaR\\Data\\Clean\\clean_Israel_GaR_data.csv"),
              stringsAsFactors = FALSE)

df = df %>%
  mutate(Date = as.Date(dates)) %>% 
  select(-dates.1,-dates)

```


```{r Process_data}

## GDP (divide flow variables with quarterly freq, stocks with rolling sum)

df = df %>% 
  filter(Date >= as.Date("1990-01-01")) %>% 
  mutate(nominal_gdp_nis_y = c(rep(NA,3),rollsum(nominal_gdp_nis,4))) %>% 
  mutate(nominal_gdp_usd_y = c(rep(NA,3),rollsum(nominal_gdp_usd,4))) %>% 
  mutate(real_gdp_nis_y = c(rep(NA,3),rollsum(real_gdp_nis,4))) %>% 
  mutate(real_gdp_usd_y = c(rep(NA,3),rollsum(real_gdp_usd,4))) %>% 
  mutate(real_gdp_yoy = real_gdp_nis_y/lag(real_gdp_nis_y,4) - 1)

## Domestic macro

df = df %>% 
  mutate(industrial_prod_yoy = Indus_prod_ind/lag(Indus_prod_ind,4) - 1) %>% 
  mutate(business_survey_yoy = business_survey/lag(business_survey,4) - 1) %>% 
  mutate(cyclical_composite_yoy = cyclical_composite/lag(cyclical_composite,4)
         - 1)

## Financial returns and spreads

df = df %>% 
  rename(term_spread = Term_spread) %>% 
  rename(interbank_spread = Interbank_spread) %>% 
  mutate(sovereign_spread = ISR_10Y_tbond - USA_10Y_tbond) %>% 
  rename(corporate_spread = Spread_CPI_corp) %>% 
  rename(fx_ba_spread = ILS_USD_spread_pct) %>% 
  rename(securities_ba_spread = securities_ba_sread) %>% 
  rename(long_term_real_rate_diff = LT_real_rate_change) %>% 
  mutate(cpi_inflation = Avg_CPI/lag(Avg_CPI,4) - 1) %>% 
  rename(inflation_expectations = Inf_exp) %>% 
  mutate(house_price_yoy = Avg_House_Price_index/lag(Avg_House_Price_index,4)
         - 1) %>% 
  rename(policy_rate = BOI_rate) %>% 
  mutate(equity_returns_qoq = TA125_Close / lag(TA125_Close,1) - 1)


## Financial volatility

df = df %>% 
  mutate(implied_yield_cpi_bond_yoy = Yld_imlp_CPI_bond /
           lag(Yld_imlp_CPI_bond,4) - 1) %>% 
  rename(short_term_bill_vol = daily_one_year_bill_rate_vol) %>% 
  rename(long_term_bond_vol = daily_ten_year_bond_rate_vol) %>% 
  rename(equity_realized_vol = daily_equity_prices_vol) %>% 
  rename(equity_implied_vol = TA_35_impl_vol)

## Leverage

df = df %>% 
  mutate(private_credit_gdp = Credit_to_non_fin_sector / nominal_gdp_nis_y) %>% 
  mutate(gov_bond_gdp = Balance_Gov_bond / nominal_gdp_nis_y) %>% 
  rename(loan_deposits_ratio = deposits_loan_ratio) %>% 
  rename(npl_ratio = NPL_ratio) %>% 
  rename(liquid_assets_st_liabilities = liquid_assets_short_term_liabilities) 


## External sector

df = df %>% 
  mutate(reer_yoy = reer / lag(reer,4) - 1) %>% 
  mutate(trade_gdp = trade_usd / nominal_gdp_usd) %>% 
  mutate(dom_investment_gdp = investment_domestic_usd / nominal_gdp_usd) %>% 
  mutate(abroad_investment_gdp = investment_abroad_usd / nominal_gdp_usd) %>% 
  mutate(fx_returns_qoq = nis_usd / lag(nis_usd,1) - 1) %>%
  mutate(fx_returns_yoy = nis_usd / lag(nis_usd,4) - 1) %>% 
  rename(fx_implied_vol = ILS_USD_impl_vol) %>% 
  rename(fx_realized_vol = daily_nis_USD_vol)
  
## Foreign

df = df %>% 
  mutate(world_indus_prod_yoy = Industrial.Production.World.SA /
           lag(Industrial.Production.World.SA, 4) - 1) %>% 
  rename(nasdaq_vol = daily_nasdaq_prices_vol) %>% 
  mutate(nasdaq_returns_qoq = daily_nasdaq_prices / lag(daily_nasdaq_prices,1)
         - 1) %>% 
  mutate(nasdaq_returns_yoy = daily_nasdaq_prices / lag(daily_nasdaq_prices,4)
         - 1) %>% 
  mutate(oil_future_qoq = daily_oil_future_prices / 
           lag(daily_oil_future_prices,1)-1) %>% 
  mutate(us_reer_eme_yoy = daily_us_reer_eme / lag(daily_us_reer_eme,4) - 1)
  


```


```{r calculate_pca}

pca_list = lapply(partitions[sapply(partitions, length) > 1],
                  function(temp_part){
  
  part_df = df %>% 
    select(unlist(temp_part)[unlist(temp_part) %in% names(df)], Date) %>% 
    filter_all(all_vars(is.finite(.)))
  
  ret_list = list(pca = part_df %>%
                    select(-Date) %>% 
                    prcomp(.,center = TRUE,scale. = TRUE),
                  date_index = part_df$Date)
  
  return(ret_list)
  
})




```


```{r plot_pca, fig.height=8}

for(name in names(pca_list)){
  
if(length(pca_list[[name]]$pca$rotation[,1]) == 1){next}
  
my_title = paste0(name ,"\n",
                   round(pca_list[[name]]$pca$sdev[1] ^ 2 /
      sum(pca_list[[name]]$pca$sdev ^ 2),3) * 100,
    "% Variance explained")
  
  
bar_plot = ggplot(data.frame(Name = names(pca_list[[name]]$pca$rotation[,1]),
                  Val = pca_list[[name]]$pca$rotation[,1]),
       aes(x = reorder(Name, Val), y = Val)) +
  geom_bar(stat = "identity", width = 0.5) +
  labs(x = "", y = "", title = my_title) +
  coord_flip() +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5))


line_plot = ggplot(data.frame(ind = seq_along(pca_list[[name]]$pca$x[,1]),
                  Val = pca_list[[name]]$pca$x[,1]),
       aes(x = ind, y = Val)) + 
  geom_line() + 
  labs(x = "", y = "", title = "") + 
  theme_bw() + 
  theme(plot.title = element_text(hjust = 0.5), legend.position = "none")

plot_legend = get_legend(bar_plot )

plot_row = plot_grid(bar_plot, line_plot,nrow = 2)

print(plot_grid(plot_legend ,plot_row,
                rel_heights = c(0.05,1), ncol = 1))


}



```


```{r quantile_reg, eval=FALSE}

reg_df = lapply(names(pca_list), function(temp_name){
  
  df = data.frame(Date = as.yearqtr(pca_list[[temp_name]][["date_index"]]),
             Temp_Var = pca_list[[temp_name]][["pca"]][["x"]][,1]) %>% 
    rename(!!quo_name(temp_name) := Temp_Var)
  
  return(df)
  

}) %>% 
  reduce(inner_join, by = "Date") %>% 
  left_join(df %>%
              select(GDP_F, Date) %>%
              mutate(GDP_F = lead(GDP_F,4)),
            by = "Date") %>% 
  select(-Date)


tau_vec = c(0.05,0.1,0.25,0.5,0.75,0.9,0.95)

quant_reg_list = rq(formula = formula(GDP_F~.),tau = tau_vec,
              data = reg_df)


sum_quant_reg = summary(quant_reg_list)

names(sum_quant_reg) = paste("tau",tau_vec, sep = "=")

```

