
```{r load_prediction_libraries}

library(stargazer)

library(forcats)

```


```{r set_forecast_parameters}

theme_set(theme_bw())

forecast_parameters = list(
  win_len = 40,
  win_type_expanding = TRUE,
  df = df %>% filter(date < as.yearqtr("2020Q1"))
    )


```


```{r make_benchmark_and_realizied_df}

realized_df = df %>% 
  filter(date < as.yearqtr("2020Q1")) %>% 
  select(date, gdp) %>% 
  filter(complete.cases(.)) %>% 
  rename(realized = gdp) %>% 
  mutate(forecast_period = paste(date - 1, date, sep = "-")) %>% 
  select(-date) %>% 
  select(forecast_period, realized) %>% 
  as_tibble()

benchmark_df = get.gar.forecast(
  partitions_list = NULL,
  vars_df = df,
  target_var_name = "gdp",
  horizon_list = parameters_list$horizon_list,
  quantile_vec = parameters_list$quantile_vec,
  win_len = forecast_parameters$win_len,
  win_type_expanding = forecast_parameters$win_type_expanding) %>%
  rename_all(tolower) %>% 
  mutate(forecast_period = paste(
    date + as.numeric(horizon) * 0.25 - 1,
    date + as.numeric(horizon) * 0.25,
    sep = "-"
    )) %>%
  mutate(horizon = factor(horizon, levels = c(1,4,8,12))) %>% 
  rename(benchmark = gar_forecast)

staff_forecast_df = import.staff.forecast(raw_df = raw_df) %>% 
  as_tibble() %>% 
  rename(prediction = staff_forecast)

staff_forecast_df = list(
  name = "Staff",
  partition = list(staff = NA),
  pred_df = staff_forecast_df) %>% 
  enframe() %>% 
  pivot_wider()



# rm(benchmark_df, realized_df)

```


```{r make_models_df}

models_df = list(GaR = current_partition,
                 Macro = partitions_list$macro) %>% 
  enframe(value = "partition") %>%
  mutate(pred_df = map(partition,function(temp_part){
      temp_forecast = get.gar.forecast(
        partitions_list = temp_part,
        vars_df = df,
        target_var_name = "gdp",
        horizon_list = parameters_list$horizon_list,
        quantile_vec = parameters_list$quantile_vec,
        win_len = forecast_parameters$win_len,
        win_type_expanding = forecast_parameters$win_type_expanding)
      
      temp_forecast = temp_forecast %>% 
        filter(complete.cases(.)) %>%
        rename_all(tolower) %>% 
        mutate(forecast_period = paste(
          date + as.numeric(horizon) * 0.25 - 1,
          date + as.numeric(horizon) * 0.25,
          sep = "-"
        )) %>%
        mutate(horizon = as_factor(horizon)) %>% 
        rename(prediction = gar_forecast)
        
        
      return(temp_forecast)
      
      })) %>% 
  rbind(staff_forecast_df) %>% 
  mutate(realized = map(1:nrow(.),~realized_df)) %>% 
  mutate(benchmark = map(1:nrow(.),~benchmark_df))%>% 
  mutate(
    r2_score = pmap(.l = list(pred_df,realized, benchmark),
                    .f = function(pred_df,realized, benchmark){
                       temp_score = collect_quantile_r2_score(
                         pred_df = pred_df,
                         realized_df = realized,
                         benchmark_df = benchmark)
                       return(temp_score)
                     })
    ) %>% 
  mutate(
    pit_score = pmap(.l = list(pred_df,realized),
                     .f = function(pred_df,realized){
                       temp_score = pred_df %>% 
                         inner_join(realized_df,
                                    by = "forecast_period") %>% 
                         rename(actual_values = realized,
                                predicted_values = prediction) %>% 
                         quantile.pit.score()
                       
                       return(temp_score)
                     }))


```


```{r plot_r2_goodness_of_fit}

models_df %>% 
  select(name, r2_score) %>% 
  unnest(c(name,r2_score)) %>% 
  mutate(horizon = factor(horizon, levels = c(1,4,8,12))) %>% 
  ggplot(aes(x = quantile, y = score, fill = name)) + 
  geom_col(position = "dodge") + 
  xlab(NULL) + ylab(NULL) + ggtitle("quantile R2 score") + 
  scale_fill_viridis_d(option = "plasma") + 
  facet_wrap(~horizon) + 
  theme(legend.position = "bottom", legend.title = element_blank())
```


```{r plot_pit_goodness_of_fit}

pit_score_df = models_df %>% 
  select(name, pit_score) %>% 
  unnest(pit_score) %>% 
  mutate(name = map_chr(name,~.)) %>% 
  mutate(quantile = as.numeric(quantile)) 

intercept_df = models_df$benchmark[[1]] %>% 
  left_join(models_df$realized[[1]], by = "forecast_period") %>% 
  rename(actual_values = realized, predicted_values = benchmark) %>% 
  select(date,actual_values,predicted_values,quantile, horizon) %>% 
  filter(complete.cases(.)) %>% 
  quantile.pit.score() %>% 
  mutate(name = "Intercept") %>% 
  select(names(pit_score_df)) %>% 
  mutate(quantile = as.numeric(quantile))


pit_score_df %>% 
  bind_rows(intercept_df) %>% 
  # filter(!name == "GaR") %>% 
  mutate(horizon = factor(horizon, levels = c(1,4,8,12))) %>% 
  ggplot(aes(x = quantile, y = pit, group = name, color = name)) + 
  geom_line() +
  geom_abline(slope = 1, intercept = 0, linetype = "dashed") + 
  xlab(NULL) + ylab(NULL) + ggtitle("PIT score") + 
  scale_color_viridis_d(option = "plasma") + 
  scale_x_continuous(breaks = c(0.05,0.25,0.5,0.75,0.95),
                   labels = c(0.05,0.25,0.5,0.75,0.95)) +
  facet_wrap(~horizon) + 
  theme(legend.position = "bottom", legend.title = element_blank())

rm(pit_score_df, intercept_df)

```

