
\subsection{Variable choice}

credit is an important variable, used extensively in the literature. The
transfomation ranges from credit gap (deviation from long term trend) such as
in @Alessandri2019 to credit to gdp ratio such as in @Aikman2019.

Financial conditions is represented either by a dedicated index (FCI) or by some
aggregation of term spreads, interbank spreads, corporate spreads, sovereign
spreads, long-term interest rates, policy rates, equity returns and equity
volatility as in [@Aikman2019]


\subsection{Data}

Our data includes `r ncol(df)` variables
(at quarterly frequency) for
`r paste(range(df$date), collapse = "-")` period.

The following transformations were performed:

\begin{enumerate}
  \item
  Selected variables(real activity, prices, credit, etc) are transformed
  to YoY rates of change.
\end{enumerate}


\subsection{Data structure}

```{r plot_data_structure, fig.height=8}

ggplot(df %>%
  mutate_at(.vars = vars(-date),
            .funs = list(~is.na(.))) %>%
  gather(key = Indicator, value = Missing, -date) %>% 
    mutate(Missing = as.factor(Missing)) %>% 
    group_by(Indicator) %>% 
    mutate(Miss_count = sum(Missing == TRUE)) %>% 
    ungroup(),
  aes(x = date, y = reorder(Indicator, Miss_count),color = Missing)) + 
  geom_point(size = 0.6) + 
  scale_color_manual(values = c("FALSE" = "lightgray",
                                "TRUE" = "magenta")) +
  scale_x_yearqtr(format = "%YQ%q",n = 25) + 
  labs(x = "",y = "", title = "Missing data structure") + 
  theme_bw() + 
  theme(legend.position = "bottom",
        axis.text.x = element_text(angle = 45, vjust = 0.5),
        axis.text.y = element_text(size = 4),
        plot.title = element_text(hjust = 0.5))

```

