---
title: "GaR analysis"
output:
  rmarkdown::pdf_document:
    latex_engine: xelatex
    number_sections: true
    includes:
            in_header: C:\\Users\\Misha\\Documents\GaR\\GaR-preamble.tex

vignette: >
  %\VignetteIndexEntry{GaR analysis}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF_8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE, echo = FALSE, message = FALSE,warning = FALSE,
  comment = "#>"
)
```


```{r setup}

devtools::load_all()

library(GaRPackg)

setwd("C:\\Users\\Misha\\Documents\\GaRPackg\\vignettes")
```


```{r load_libraries}

library(gghighlight)

library(tidyselect)

library(tidyverse)

library(quantreg)

library(rlang)

```


```{r Import_data}

osnat_list = import.osnat.data()

michael_list = import.michael.data()

raw_df = full_join(osnat_list$osnat_df, michael_list$michael_df,
               by = "Date") %>% 
  arrange(Date)

```


```{r Import_BoI_forecast_data}

df_forecast = read.csv(paste0("C:\\Users\\Misha\\Documents\\Data\\BOI\\DSGE",
                              "\\DSGE and staff forecasts.csv"),
                       stringsAsFactors = FALSE)

names(df_forecast)[1] = "Date"

df_forecast = df_forecast  %>% 
  mutate(Date = as.Date(Date, format = "%m/%d/%Y")) %>% 
  mutate(Date = as.yearqtr(Date)) %>% 
  filter_at(.vars = vars(-Date),.vars_predicate = any_vars(!is.na(.))) %>% 
  rename_at(.vars = vars(-Date),.funs = list(~gsub("bi.staff_fct_","",.))) %>% 
  rename_at(.vars = vars(-Date),.funs = list(~gsub("_08","",.))) %>%
  rename_at(.vars = vars(-Date),.funs = list(~gsub("\\.Q$","",.)))



```


```{r Set_parameters}

quantile_vec = c(0.05,0.25,0.5,0.75,0.95)

horizon_list = list(1,4,8,12)


```


```{r Set_partitions}

partitions = list(Dom_Real = list("GDP_F","Ind_Prod_Israel",
                                  "C_FP","G_NDEFIMP_FP","INV_FP",
                                  "INV_NI_FP","EXP_ND_FP","IMP_ND_FP",
                                  "STARTUP_FP"),
                  Dom_Prices = list("CPI","breakeven_inflation_1Y",
                                    "breakeven_inflation_2_3_fwd",
                                    "breakeven_inflation_5_10_fwd",
                                    "CPI_season_adj",
                                    "CPI_no_house_fruits_season_adj",
                                    "CPI_no_house_season_adj",
                                    "CPI_no_house","CPI_no_fruits"),
                  Rates = list("BOI_rate","Telbor_1Y","real_rate_1",
                               "real_rate_2_3_fwd","real_rate_5_10_fwd"),
                  External = list("CA","ILS_USD","ILS_EURO",
                                  "ILS_Yen","ILS_GBP"),
                  Global = list("VIX","Ind_Prod_advanced",
                                "Brent","Commodity_Non_Energy",
                                "gdp_us","gdp_euro","gdp_japan",
                                "gdp_uk","infl_us","infl_euro",
                                "infl_japan","infl_uk","rate_euro","rate_us",
                                "rate_uk","rate_japan","US_10","EU_10",
                                "UK_10","JPN_10", "US_5","EU_5","UK_5","JPN_5",
                                "IMP_OECD"),
                  Labor = list("Labor_pop","Wage","EMP","Unemp_rate",
                               "Labor_force","Vacancies_Rate"),
                  National_Security = list("Tourists"),
                  Spread = list("Spread_CPI_corp",
                                "ILS_USD_spread_pct","Interbank_spread",
                                "Sovereigh_spread",
                                "Term_spread"),
                  Volatility = list("ILS_USD_impl_vol","TA_35_impl_vol"),
                  Returns = list("TA125_Close"),
                  Credit = list("Credit_to_non_fin_sector",
                                "Avg_House_Price_index"))



```


```{r Modify_partitions}

partitions$Risk = partitions[c("Spread","National_Security",
                                      "Volatility")] %>% 
  setNames(NULL) %>% 
  unlist() %>% 
  as.list()

partitions = partitions[!names(partitions) %in% c("Spread",
                                                 "National_Security",
                                                 "Volatility")]

partitions$Fin_Cycle = partitions[c("Credit","Returns")] %>% 
  setNames(NULL) %>% 
  unlist() %>% 
  as.list()

partitions = partitions[!names(partitions) %in% c("Credit","Returns")]

```


```{r Process_data}

vars_to_rates = c("Ind_Prod_advanced","Ind_Prod_Israel",
                  "GDP_F","C_FP","G_NDEFIMP_FP","INV_FP",
                  "INV_NI_FP","EXP_ND_FP","IMP_ND_FP","STARTUP_FP",
                  "CPI_season_adj","CPI_no_house_fruits_season_adj",
                  "CPI_no_house_season_adj","CPI", "CPI_no_house",
                  "CPI_no_fruits","ILS_USD","ILS_EURO","ILS_Yen","ILS_GBP",
                  "gdp_us","gdp_euro","gdp_japan","gdp_uk",
                  "Brent","Commodity_Non_Energy","Labor_pop",
                  "Wage","EMP","Labor_force","Tourists","TA125_Close",
                  "Avg_House_Price_index","Credit_to_non_fin_sector",
                  "IMP_OECD")

df = raw_df %>% 
  select(-GDP_F, -GDP_no_tax,-GDP_season_adj) %>% 
  rename(GDP_F = GDP_no_startup)

df = df %>% 
  mutate_at(.vars = vars(unlist(partitions$Dom_Real),CA),
            .funs = list(~c(rep(NA,3),rollsum(.,4))))

# Normalize CA by GDP

df = raw_df %>% 
  mutate(CA = CA / GDP_F)


# Transform variables to rates of change YoY

df = df %>% 
  mutate_at(vars(vars_to_rates),
            .funs = list(~./lag(.,4)-1))


# Calculate difference

df = df %>%
  mutate(real_rate_2_3_fwd = real_rate_2_3_fwd - real_rate_5_10_fwd) %>%
  mutate(BOI_rate = BOI_rate - real_rate_5_10_fwd) %>%
  mutate(US_5 = US_5 - US_10) %>%
  mutate(EU_5 = EU_5 - EU_10) %>%
  mutate(JPN_5 = JPN_5 - JPN_10) %>%
  mutate(Ger_5 = Ger_5 - Ger_10) %>%
  mutate(UK_5 = UK_5 - UK_10) %>%
  mutate(rate_us = rate_us - US_10) %>%
  mutate(rate_euro = rate_euro - EU_10) %>%
  mutate(rate_japan = rate_japan - JPN_10) %>%
  mutate(rate_uk = rate_uk - UK_10) %>%
  select(-ends_with("10"))

```


```{r drop_short_series}

drop_series = c("Vacancies_Rate","Telbor_1Y","STARTUP_FP",
                "Term_spread","Sovereigh_spread",
                "Interbank_spread","LT_real_rate_change",
                "TA125_Close","Indus_prod_ind","ILS_EURO",
                "breakeven_inflation_5_10_fwd")

df = df %>% 
  select(-drop_series)

```


```{r calculate_pca}


pca_list = lapply(partitions[sapply(partitions, length) > 1],
                  function(temp_part){
  
  part_df = df %>% 
    select(unlist(temp_part)[unlist(temp_part) %in% names(df)], Date) %>% 
    filter_all(all_vars(is.finite(.)))
  
  ret_list = list(pca = part_df %>%
                    select(-Date) %>% 
                    prcomp(.,center = TRUE,scale. = TRUE) %>% 
                    align.pca(1),
                  date_index = part_df$Date)
  
  return(ret_list)
  
})

```


```{r get_quantile_regressions}

reg_df = lapply(names(pca_list), function(temp_name){
  
  temp_df = data.frame(Date = pca_list[[temp_name]]$date_index,
                       PCA = pca_list[[temp_name]]$pca$x[,1],
                       stringsAsFactors = FALSE)
  
  names(temp_df) = c("Date",temp_name)
  
  return(temp_df)
  
  
  
  
}) %>% 
  reduce(inner_join, by = "Date") %>% 
  arrange(Date)%>% 
  inner_join(df %>% 
              select(Date, GDP_F), by = "Date")

for(temp_horizon in unlist(horizon_list)){
  
  temp_var = paste("GDP_growth",temp_horizon,sep = "_")
  
  reg_df = reg_df %>% 
    mutate(!!sym(temp_var) := lead(GDP_F,temp_horizon))

}


qregs_results = lapply(horizon_list, function(temp_horizon){

  dep_var = paste0("GDP_growth_", temp_horizon)
  
  qreg_list = rq(formula = formula(paste0(dep_var,"~.")),
               tau = quantile_vec,
               data = reg_df %>% 
                 select(-Date) %>% 
                 select(names(.)[!grepl("GDP",names(.))], dep_var))  
  
  return(qreg_list)
  
  
})

names(qregs_results) = horizon_list

```

\section{PCA results}

```{r plot_pca, child="GaR-Partition-Evaluation.Rmd", eval=FALSE}


```


\section{Quantile regression results}

```{r plot_quantile_reg, child="GaR-Quantile-Regression.Rmd"}

```


\section{Prediction}

```{r , child="GaR-Prediction-Comparison.Rmd", eval=FALSE}

```




\section {Appendix}

```{r child="GaR-Appendix.Rmd", eval=FALSE}

```

