---
title: "HaR analysis"
bibliography: C:\\Users\\internet\\Documents\\Refrences\\GaR.bib
fontsize: 11pt
output:
  rmarkdown::pdf_document:
    latex_engine: xelatex
    number_sections: true
    includes:
            in_header: C:\\Users\\internet\\Documents\\GaRpckg\\GaR-preamble.tex

vignette: >
  %\VignetteIndexEntry{GaR analysis}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF_8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE, echo = FALSE, message = FALSE,warning = FALSE,
  comment = "#>"
)
```


```{r setup}

devtools::load_all()

library(GaRPackg)

# setwd("C:\\Users\\Misha\\Documents\\GaRPackg\\vignettes")
```


```{r load_libraries}

library(readxl)

library(tidyselect)

library(tidyverse)

library(quantreg)

library(corrplot)

library(stargazer)

library(xtable)

```


```{r Import_gar_data}

raw_data = list(osnat_list = import.osnat.data(),
                michael_list = import.michael.data())

raw_data$raw_df = full_join(raw_data$osnat_list$osnat_df,
                            raw_data$michael_list$michael_df,
                            by = "Date") %>% 
  arrange(Date)


```


```{r Import_data}

df = list(gdp_nominal = read.csv(paste0("C:\\Users\\internet\\Documents\\Data\\BOI\\",
                              "GDP_nominal_quarterly_1995Q1-2019Q4.csv"),
                            stringsAsFactors = FALSE) %>% 
       setNames(c("Date","GDP_Nominal")) %>% 
       mutate(Date = as.yearqtr(Date, format = "%d/%m/%Y")),
     gdp_real = read.csv(paste0("C:\\Users\\internet\\Documents\\Data\\BOI\\",
                                "GDP_real_quarterly_1995Q1-2019Q4.csv"),
                         stringsAsFactors = FALSE) %>% 
       setNames(c("Date","GDP_real")) %>% 
       mutate(Date = as.yearqtr(Date, format = "%d/%m/%Y"))) %>% 
  reduce(inner_join, by = "Date")

df = df %>% 
  mutate_at(.vars = vars(starts_with("GDP")),
            .funs = list(~as.numeric(str_remove_all(.,","))))

df = df %>% 
  inner_join(raw_data$raw_df %>% 
               select(Date, House_Price,Credit,BOI_rate) %>% 
               rename(House = House_Price),
             by = "Date")


```


```{r Set_parameters}

setwd("C:\\Users\\internet\\Documents\\GaRpckg\\vignettes")

results = list()

parameters_list = list()

parameters_list$quantile_vec = c(0.05,0.25,0.5,0.75,0.95)

parameters_list$horizon_list = list(1,8,12)



```


```{r annulized_growth_rates}

growth_rates = df %>% 
  select(Date,House) %>% 
  filter(complete.cases(.)) %>% 
  arrange(Date) %>% 
  mutate(Growth_1_year = (House / lag(House,4) - 1)) %>% 
  mutate(Growth_3_year = (House / lag(House,12) - 1) / 3)

mean_growth_rates = sapply(growth_rates[,c("Growth_1_year","Growth_3_year")], mean,
                          na.rm = TRUE)

```


```{r preprocessing}

processed_df = df %>% 
  mutate_at(.vars = vars(GDP_Nominal,GDP_real,House),
            .funs = list(qoq = ~ (. / lag(.,1) - 1) * 100)) %>% 
  mutate_at(.vars = vars(GDP_Nominal,GDP_real,House),
            .funs = list(yoy = ~ (. / lag(.,4) - 1) * 100)) %>% 
  mutate(Credit_to_GDP = GDP_Nominal / Credit) %>% 
  mutate_at(vars(House_qoq, House_yoy),.funs = list(lead = ~lead(.,4)))

```

\section{Descriptive Stats}

```{r output_desc_stats, results="asis"}

stargazer(processed_df %>% 
            select_at(vars(ends_with("qoq"),ends_with("yoy"), "Credit_to_GDP")),
          summary = TRUE, header = FALSE)

```


```{r plot_house_price}

ggplot(processed_df %>% 
         select(Date, House_yoy),
       aes(x = Date, y = House_yoy)) + 
  geom_line() + 
  scale_y_continuous(labels = function(x){paste0(x,"%")}) + 
  labs(x = "", y = "", title = "House price changes (YoY)") + 
  theme_bw() + 
  theme(legend.position = "bottom", plot.title = element_text(hjust = 0.5))
  
  
  
```


```{r hist_house_growth}

ggplot(growth_rates %>% 
         select(-House) %>% 
         gather(key = Horizon,value = Val,-Date), aes(x = Val * 100, fill = Horizon)) + 
  geom_histogram(position = "dodge") + 
  scale_fill_manual(values = c(Growth_1_year = "darkgreen", Growth_3_year = "red")) + 
  theme_bw() + 
  theme(legend.position = "bottom", legend.title = element_blank())

```


```{r fitting_model, eval=FALSE}

mod_res = list()

mod_res$gdp = rq(formula = "House_qoq_lead ~ GDP_real_qoq", tau = c(0.05,0.5,0.95),
         data = processed_df)

mod_res$rate = rq(formula = "House_qoq_lead ~ BOI_rate", tau = c(0.05,0.5,0.95),
         data = processed_df)

```


```{r}

coef_df = lapply(names(mod_res), function(temp_name){
  
  coef_table = mod_res[[temp_name]]$coefficients %>% 
  t() %>% 
  as.data.frame() %>% 
  setNames(c("Intercept","Slope")) %>% 
  mutate(Quantile = str_remove(rownames(.),"tau= ")) %>% 
  mutate(Variable = temp_name)
  
  return(coef_table)
  
}) %>% 
  bind_rows() %>% 
  mutate(Color = case_when(Quantile == "0.05" ~ "red",
                         Quantile == "0.50" ~ "orange",
                         Quantile == "0.95" ~ "darkgreen"))



```


```{r, plot_gdp, eval=FALSE}

ggplot(processed_df %>% 
  select(GDP_real_qoq, House_qoq_lead), aes(x = GDP_real_qoq, y = House_qoq_lead)) + 
  geom_point() + 
  geom_abline(slope = coef_df$Slope[coef_df$Variable == "gdp"],
              intercept = coef_df$Intercept[coef_df$Variable == "gdp"],
              color = coef_df$Color[coef_df$Variable == "gdp"]) + 
  theme_bw()

```



```{r, plot_rate, eval=FALSE}

ggplot(processed_df %>% 
  select(BOI_rate, House_qoq_lead), aes(x = BOI_rate, y = House_qoq_lead)) + 
  geom_point() + 
  geom_abline(slope = coef_df$Slope[coef_df$Variable == "rate"],
              intercept = coef_df$Intercept[coef_df$Variable == "rate"],
              color = coef_df$Color[coef_df$Variable == "rate"]) + 
  theme_bw()

```

