---
title: "Inflation Risks in Israel - test"
---


```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE, echo = FALSE, message = FALSE,
  warning = FALSE, comment = "#>"

)
```


```{r init_setup}

devtools::load_all()

library(ggcorrplot)

library(mFilter)

library(tidyverse)

library(lubridate)

library(slider)

library(cowplot)

library(broom)

library(gghighlight)

library(glue)

setwd(paste0(
  file.path(Sys.getenv("USERPROFILE"),fsep = "\\"),
  "\\Documents\\GaRPackg\\vignettes"))


```

```{r set_params}

partitions_list = list(
  inflation = c("cpi"),
  exchange_rate = c("nis_usd"),
  oil_p = c("brent_usd"),
  output_gap = c("meshulav_gap"),
  expectation = c("beir5y5y")
)

partitions_list_zlb = c(partitions_list,
                        list(zlb_dummy = "zlb_indicator"))

partitions_list_zlb_complete = c(partitions_list_zlb,
                                 list(cpi_zlb = "cpi_zlb",
                                      nis_usd_zlb = "nis_usd_zlb",
                                      brent_usd_zlb = "brent_usd_zlb",
                                      meshulav_gap_zlb = "meshulav_gap_zlb",
                                      beir5y5y_zlb = "beir5y5y_zlb"))

rm(partitions_list, partitions_list_zlb)


horizon_list=c(1,12)

quantile_vec=c(0.10,0.25,0.5,0.75,0.90)



theme_set(theme_bw() + 
            theme(title = element_text(size = 20),
                axis.text = element_text(size = 15),
                axis.title = element_text(size = 15),
                strip.text = element_text(size = 15),
                legend.position = "bottom",
                legend.title = element_blank(),
                legend.text = element_text(size = 15)))


my_levels = c(
      "cpi",
      "beir5y5y" ,
      "meshulav_gap",
      "brent_usd",
      "nis_usd",
      "zlb_indicator",
      "cpi_zlb",
      "nis_usd_zlb",
      "brent_usd_zlb",
      "meshulav_gap_zlb",
      "beir5y5y_zlb"
      
    )

my_labels = c(
      "Inflation",
      "Expectations",
      "Output Gap",
      "Oil prices",
      "Exchange Rate",
      "ZLB",
      "ZLB_Inflation",
      "ZLB_Expectations",
      "ZLB_Output Gap",
      "ZLB_Oil prices",
      "ZLB_Exchange Rate"
    )

labels_df = tibble(
  level = c("exp_int",my_levels),
  label = c("Exp. and Intercept",my_labels
  )
)

```


```{r temp_functions}

get_factors_df = function(iar_object){
  
  factors_cont_df = iar_object %>%
  extract_factor_contribution_from_gar_model(target_quantile = "0.25") %>%
  mutate(quantile = 0.25) %>%
  bind_rows(iar_object %>%
  extract_factor_contribution_from_gar_model(target_quantile = "0.75") %>%
  mutate(quantile = 0.75)) %>%
  bind_rows(iar_object %>%
  extract_factor_contribution_from_gar_model(target_quantile = "0.5") %>%
  mutate(quantile = 0.5)) %>%
  filter(horizon == 12) %>% 
  filter(date >= as.yearmon("Jan 2007")) %>% 
  pivot_longer(-c(date, quantile, horizon))
  
  factors_cont_df = factors_cont_df %>% 
  mutate(name = factor(name)) %>% 
  mutate(name = fct_collapse(name,
                             cpi = c("cpi", "cpi_zlb"),
                             nis_usd = c("nis_usd", "nis_usd_zlb"),
                             brent_usd = c("brent_usd", "brent_usd_zlb"),
                             meshulav_gap = c("meshulav_gap", "meshulav_gap_zlb"),
                             beir5y5y = c("beir5y5y", "beir5y5y_zlb"),
                             intercept = c("intercept","zlb_indicator"))) %>% 
  group_by(date, horizon,quantile, name) %>% 
  summarise(value = sum(value), .groups = "drop")
  
  return(factors_cont_df)
  
  
}

get_skew_plot = function(temp_factors_cont_df,
                         iqr_df,means_vec,median_mean){
  
  skew_plot = temp_factors_cont_df %>% 
  pivot_wider(id_cols = c(date,name, horizon), names_from = quantile,
              names_prefix = "q_") %>% 
  left_join(iqr_df, by = c("date", "horizon")) %>% 
  mutate(skew_cont = (q_0.75 + q_0.25 - 2 * q_0.5) / iqr) %>% 
  select(-starts_with("q_"),-horizon,-iqr) %>% 
  group_by(date = as.yearqtr(date), name) %>% 
  summarise(across(everything(),mean, na.rm = TRUE), .groups = "drop")  %>% 
  pivot_wider(names_from = name, values_from = skew_cont) %>% 
  mutate(intercept = intercept - means_vec$skew) %>%
  mutate(skew = skew - means_vec$skew) %>%
  pivot_longer(-c(date,skew))
  
  return(skew_plot)
  
}

get_disp_plot = function(temp_factors_cont_df,
                         iqr_df,means_vec,median_mean){
  
  disp_plot = temp_factors_cont_df %>% 
  pivot_wider(id_cols = c(date,name, horizon), names_from = quantile,
              names_prefix = "q_") %>% 
  left_join(iqr_df, by = c("date", "horizon")) %>% 
  mutate(iqr_cont = q_0.75 - q_0.25) %>%
  select(-starts_with("q_"),-horizon,-skew) %>% 
  group_by(date = as.yearqtr(date), name) %>% 
  summarise(across(everything(),mean, na.rm = TRUE), .groups = "drop")  %>% 
  pivot_wider(names_from = name, values_from = iqr_cont) %>% 
  mutate(intercept = intercept - means_vec$iqr) %>% 
  mutate(iqr = iqr - means_vec$iqr) %>% 
  pivot_longer(-c(date,iqr))
  
  
  return(disp_plot)

  
  
  
}

get_median_plot = function(temp_factors_cont_df,
                           iqr_df,means_vec,median_mean){
  
  median_plot = temp_factors_cont_df %>% 
  pivot_wider(id_cols = c(date,name, horizon), names_from = quantile,
              names_prefix = "q_") %>% 
  mutate(med_cont = q_0.5) %>%
  select(-starts_with("q_"),-horizon) %>% 
  group_by(date = as.yearqtr(date), name) %>% 
  summarise(across(everything(),mean, na.rm = TRUE), .groups = "drop")  %>% 
  pivot_wider(names_from = name, values_from = med_cont) %>% 
  mutate(intercept = intercept - median_mean) %>%
  pivot_longer(-c(date))
  
  
  return(median_plot)
  
}


plot_panel = function(temp_iar_analysis){
  
  temp_factors_cont_df = temp_iar_analysis %>%
  get_factors_df()
  
  iqr_df = temp_iar_analysis %>% 
  calculate_skew_and_iqr()
  
  means_vec = iqr_df %>% 
  filter(horizon == 12) %>% 
  select(skew,iqr) %>% 
  summarise(across(everything(), mean))


  median_mean = temp_iar_analysis$fitted_df %>% 
    filter(quantile == "0.5") %>% 
    pull(fitted_values) %>% 
    mean()
  
  skew_plot_df = temp_factors_cont_df %>% 
  get_skew_plot(iqr_df,means_vec,median_mean)
  
  disp_plot_df = temp_factors_cont_df %>% 
  get_disp_plot(iqr_df,means_vec,median_mean)
  
  
  median_plot_df = temp_factors_cont_df %>% 
  get_median_plot(iqr_df,means_vec,median_mean)
  
  
  skew_plot = ggplot() + 
  geom_col(aes(x = date, y = value, fill = name), data = skew_plot_df) + 
  geom_line(aes(x = date, y = skew), data = skew_plot_df, size = 1) + 
  xlab(NULL) + ylab(NULL) + ggtitle("Skewness")


  disp_plot =  ggplot() + 
    geom_col(aes(x = date, y = value, fill = name), data = disp_plot_df) + 
    geom_line(aes(x = date, y = iqr), data = disp_plot_df, size = 1) + 
    xlab(NULL) + ylab(NULL) + ggtitle("Dispersion")

  med_plot =  ggplot() + 
    geom_col(aes(x = date, y = value, fill = name), data = median_plot_df) + 
    geom_line(aes(x = date, y = value), data = median_plot_df %>% 
                group_by(date) %>% 
                summarise(value = sum(value), .groups = "drop"), size = 1) +
    xlab(NULL) + ylab(NULL) + ggtitle("Median") + 
    labs(caption = "Deviations from the mean")


  plot_legend = get_legend(disp_plot)
  
  plots_row = plot_grid(disp_plot +
              theme(legend.position = "none"),
            skew_plot +
              theme(legend.position = "none"),
            med_plot +
              theme(legend.position = "none",
                    plot.caption = element_text(hjust = 0)))
  
  print(plot_grid(plots_row, plot_legend,nrow = 2,rel_heights = c(4,1)))
  
  return(list(skew_plot_df = skew_plot_df,
              disp_plot_df = disp_plot_df,
              median_plot_df = median_plot_df))

  
}


```


```{r load_data}

raw_df = import_from_fame_template(
  paste0(
    file.path(Sys.getenv("USERPROFILE")),
    "\\OneDrive - Bank Of Israel\\Data\\BoI\\IaR_data\\data_Inflation_at_Risk_monthly.csv"
  ),data_frequency = "monthly"
)

df = raw_df %>% 
  mutate(rel_tradables = cpi_tradables / cpi_nontradables_excl_fv_hous) %>%
  preprocess_df(
    vars_to_yoy = c(
      "cpi",
      "cpi_excl_fv",
      "cpi_excl_fv_hous",
      "cpi_excl_hous",
      "rel_tradables",
      "cpi_oecd",
      "cpi_us",
      "cpi_euro",
      "debt_business",
      "debt_households",
      "house_price",
      "ta125"
    ),
    vars_to_percent_changes = c("nis_usd",
                                "neer",
                                "brent_usd",
                                "brent_nis",
                                "non_energy_p"),
    convert_to_percent_units = TRUE
  ) %>%
  mutate(target = target * 100) %>% 
  mutate(cpi_orig = cpi) %>% 
  mutate(cpi = cpi_excl_fv_hous) %>% 
  mutate(cpi_lag = lag(cpi)) %>% 
  filter(year(date) >= 2004 & year(date) <= 2019)

filter_obj =  hpfilter(df$madad_meshulav,freq = 1600)

df = df %>% 
  mutate(meshulav_gap = filter_obj$cycle / filter_obj$trend[,1] * 100)

df_2014 = df %>% 
  select(date, any_of(unlist(partitions_list_zlb_complete,
                             use.names = FALSE))) %>% 
  mutate(zlb_indicator = if_else(year(date) >= 2014,1,0)) %>% 
  mutate(across(c("cpi","nis_usd","brent_usd","meshulav_gap","beir5y5y"),
                ~ . * zlb_indicator,.names = "{.col}_zlb"))

df_2014_sep = df %>% 
  select(date, any_of(unlist(partitions_list_zlb_complete,
                             use.names = FALSE))) %>% 
  mutate(zlb_indicator = if_else(date >= as.yearmon("Sep 2014"),
                                 1,0)) %>% 
  mutate(across(c("cpi","nis_usd","brent_usd","meshulav_gap","beir5y5y"),
                ~ . * zlb_indicator,.names = "{.col}_zlb"))

```

```{r run_analysis}

iar_analysis_2014 = run_GaR_analysis(
  partitions_list = partitions_list_zlb_complete,
  vars_df = df_2014,
  target_var_name = "cpi",
  horizon_list = horizon_list,
  quantile_vec = quantile_vec,
  pca.align.list = list(
    output_gap = list("output_gap", TRUE),
    expectation = list("beir5y5y", TRUE)
  )
)

iar_analysis_2014_sep = run_GaR_analysis(
  partitions_list = partitions_list_zlb_complete,
  vars_df = df_2014_sep,
  target_var_name = "cpi",
  horizon_list = horizon_list,
  quantile_vec = quantile_vec,
  pca.align.list = list(
    output_gap = list("output_gap", TRUE),
    expectation = list("beir5y5y", TRUE)
  )
)

rm(filter_obj, my_labels, my_levels, horizon_list, quantile_vec)

```


```{r plot_factor_decomposition_2014}

plots_2014 = plot_panel(iar_analysis_2014)


```

```{r plot_factor_decomposition_2014_sep}

plots_2014_sep = plot_panel(iar_analysis_2014_sep)


```


```{r check_out_skewness_january}

plots_2014 %>%
  pluck("skew_plot_df") %>%
  mutate(group_ind = "january") %>%
  bind_rows(plots_2014_sep %>%
              pluck("skew_plot_df") %>%
              mutate(group_ind = "september")) %>%
  ggplot(aes(x = date, y = skew, color = group_ind)) +
  geom_line()


plots_2014 %>% 
  pluck("skew_plot_df") %>% 
  mutate(group_ind = "january") %>% 
  ggplot(aes(x = date, y = value, fill = name)) + 
  geom_col()

```

```{r find_outlier}

plots_2014 %>% 
  pluck("skew_plot_df") %>% 
  filter(abs(value) > 10)

```

