
```{r set_params}

pca_list = results$pca

plot_names_list = list("Macro","Global","Fin. Conditions",
                       "Fin. Cycle")

names(plot_names_list) = names(pca_list)

```


```{r get_quantile_df_osnat}

quantile_df_osnat = lapply(names(results$qreg_result),
                               function(temp_name){

    temp_forecast = predict(results$qreg_result[[temp_name]],
                       newdata = results$reg_df)
    
    temp_forecast  = temp_forecast %>% 
      as.data.frame() %>% 
      mutate(date = results$reg_df$date) %>% 
      setNames(str_remove_all(names(.),"tau= ")) %>% 
      gather(key = Quantile,value = GaR,-date) %>% 
      mutate(Horizon = temp_name)
    
    return(temp_forecast)
  
}) %>% 
  bind_rows() %>% 
  mutate(date = as.yearqtr(date)) %>% 
  mutate(Horizon = factor(Horizon, levels = c("1","8","12"))) %>% 
  mutate(Quantile = str_replace(Quantile,"0.50","0.5")) %>% 
  spread(key = Quantile, value = GaR)


write_csv(quantile_df_osnat, paste0(file.path(Sys.getenv("USERPROFILE"),"Desktop",fsep="\\"),
                                    "\\quantiles.csv"))


```


```{r charts_1_vs_5}

coeff_df = lapply(names(results$qreg_result),
                  function(temp_name){
  
  temp_coeff_df = results$qreg_result[[temp_name]]$coefficients %>% 
    as.data.frame() %>% 
    rename_all(.funs = list(~str_remove_all(.,"tau= "))) %>% 
    mutate(Partition = rownames(.)) %>% 
    gather(key = Quantile,value = Coeff, - Partition) %>% 
    mutate(Horizon = temp_name)
    
  
  return(temp_coeff_df)

}) %>% 
  bind_rows() %>% 
  mutate(Horizon = factor(Horizon, levels = c(1,8,12))) %>% 
  filter(!Partition == "(Intercept)") %>% 
  mutate(Partition = str_remove_all(Partition,"_xreg"))
  
my_lab = function(string){
  
  paste0("h = ", string)
  
}

dom_macro_plot = ggplot(coeff_df %>% 
         filter(Partition == "Dom_Macro") %>% 
         filter(Horizon %in% c(1,12)),
         aes(x = Quantile, y= Coeff)) + 
  geom_col(width = 0.5) + 
  geom_hline(yintercept = 0, linetype = "dashed", color = "blue") + 
  labs(x = "Quantile", y = "",
       title = "Macro coefficients") + 
  facet_wrap(~ Horizon, labeller = labeller(Horizon = my_lab)) + 
  theme_bw() + 
  theme(plot.title = element_text(hjust = 0.5))


fin_cycle_plot = ggplot(coeff_df %>% 
         filter(Partition == "FinCycle") %>% 
         filter(Horizon %in% c(1,12)),
         aes(x = Quantile, y= Coeff)) + 
  geom_col(width = 0.5) + 
  geom_hline(yintercept = 0, linetype = "dashed", color = "blue") + 
  labs(x = "Quantile", y = "",
       title = "Fin.Cycle coefficients") + 
  facet_wrap(~ Horizon,labeller = labeller(Horizon = my_lab)) + 
  theme_bw() + 
  theme(plot.title = element_text(hjust = 0.5))

rm(my_lab)

ggsave(filename = paste0(file.path(Sys.getenv("USERPROFILE"),
                                   "Desktop",fsep="\\"),
                         "\\dom_macro_plot.png"),
       plot = dom_macro_plot,
       device = "png",width = 5,height = 4.5,units = "in",dpi = 300)

ggsave(filename = paste0(file.path(Sys.getenv("USERPROFILE"),
                                   "Desktop",fsep="\\"),
                         "\\fin_cycle_plot.png"),
       plot = fin_cycle_plot,
       device = "png",width = 5,height = 4.5,units = "in",dpi = 300)

```


```{r plot_pca_loadings}

pca_plots = lapply(names(pca_list), function(name){
  
  pca_var = round(pca_variance$Variance
                  [pca_variance$Name == name] * 100,0)
  
  bar_plot = ggplot(data.frame(Name = names(pca_list[[name]]$pca$rotation[,1]),
                  Val = pca_list[[name]]$pca$rotation[,1]),
       aes(x = reorder(Name, Val), y = Val)) +
  geom_bar(stat = "identity", width = 0.5) +
  labs(x = "", y = "", title = paste0(
    plot_names_list[[name]], " (" ,pca_var, "%)")) +
  coord_flip() +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5, size = 40),
        axis.text = element_text(size = 20))
  
  rm(pca_var)
  
  return(bar_plot)
  

})

panel_plot = plot_grid(plotlist = pca_plots)

save_plot(filename = paste0(file.path(Sys.getenv("USERPROFILE"),
                                   "Desktop",fsep="\\"),
                         "\\pca_loadings.png"),
          plot = panel_plot, nrow = 4,ncol = 2,
          base_height = 4,base_width = 8)


```


```{r plot_partiton_timeseries}


pca_timeseries_plots = lapply(names(pca_list), function(name){
  
  ggplot(data.frame(x = pca_list[[name]]$time_index,
                  y = pca_list[[name]]$pca_obj$x[,1]),
         aes(x = x, y = y)) + 
    geom_line() + 
    labs(title = plot_names_list[name], x = "", y = "") + 
    scale_x_yearqtr() + 
    theme_bw() + 
    theme(plot.title = element_text(hjust = 0.5, size = 40),
          axis.text = element_text(size = 30))

  })


save_plot(filename = paste0(file.path(Sys.getenv("USERPROFILE"),
                                   "Desktop",fsep="\\"),
                         "\\pca_timeseries.png"),
          plot = plot_grid(plotlist = pca_timeseries_plots),
          nrow = 4,ncol = 2,base_height = 4,base_width = 8)


```


```{r risk_assymetry}

dist_quantile_df = results$gar_fitted_df %>% 
  spread(key = Quantile,value = GaR_fitted) %>% 
  rename_at(.vars = vars(grep("\\d",names(.),value = TRUE)),
            .funs = list(~paste0("Q_",.))) %>% 
  group_by(Horizon) %>% 
  mutate(Skew = (0.5 * Q_0.75 + 0.5 * Q_0.25 - Q_0.5) /
           (0.5 * Q_0.75 - 0.5 * Q_0.25))



risk_assymetry_plot = ggplot(dist_quantile_df,
                             aes(x = date, y = Skew)) + 
  geom_line() + 
  geom_hline(yintercept = c(-0.5,0.5), linetype = "dashed",
             color = "blue") +
  geom_hline(yintercept = 0, linetype = "dashed", color = "black") + 
  labs(x = "", y = "", title = "Risk asymmetry") + 
  facet_wrap(~Horizon, scales = "free", ncol = 1) + 
  theme_bw() + 
  theme(legend.position = "bottom",
        plot.title = element_text(hjust = 0.5))

ggsave(filename = paste0(file.path(Sys.getenv("USERPROFILE"),
                                   "Desktop",fsep="\\"),
                         "\\risk_assymetry.png"),
       plot = risk_assymetry_plot,
       device = "png",width = 5,height = 4.5,units = "in",dpi = 300)



```


```{r median_variance_scatter_plot}

dist_quantile_df = lapply(names(results$qreg_result),
                   function(temp_name){
                     
                     date_vec = results$reg_df$date
                     
                     date_vec = date_vec[1:(length(date_vec) - 
                                              as.numeric(temp_name))]
                     
                     temp_df = results$qreg_result[[
                       temp_name]]$fitted.values %>% 
                       as.data.frame() %>% 
                       setNames(unlist(parameters_list$quantile_vec)) %>% 
                       mutate(date = date_vec) %>% 
                       mutate(OLS = results$ols_reg[[temp_name]]$fitted.values) %>% 
                       gather(key = Quantile,value = GaR,-date) %>% 
                       mutate(Horizon = temp_name)
                   
                       return(temp_df)
                     
                   }) %>% 
  bind_rows() %>% 
  mutate(date = as.yearqtr(date)) %>% 
  mutate(Horizon = factor(Horizon, levels = c("1","8","12"))) %>% 
  spread(key = Quantile,value = GaR) %>% 
  rename_at(.vars = vars(grep("\\d",names(.),value = TRUE)),
            .funs = list(~paste0("Q_",.))) %>% 
  group_by(Horizon) %>% 
  mutate(IQR = Q_0.95 - Q_0.05) %>% 
  mutate(Up_dist = Q_0.95-Q_0.5) %>% 
  mutate(Down_dist = Q_0.5-Q_0.05) %>% 
  mutate(RA = Up_dist - Down_dist)

median_variance_plot  = ggplot(dist_quantile_df %>% 
         select(Horizon, IQR, Q_0.5), aes(x = IQR, y = Q_0.5)) + 
  geom_point() + 
  stat_smooth(method = "lm") + 
  facet_wrap(~Horizon) + 
  labs(x = "Variance", y = "Median", title = "Median vs Variance") +
  theme_bw() + 
  theme(plot.title = element_text(hjust = 0.5))



ggsave(filename = paste0(file.path(Sys.getenv("USERPROFILE"),
                                   "Desktop",fsep="\\"),
                         "\\median_variance.png"),
       plot = median_variance_plot,
       device = "png",width = 5,height = 4.5,units = "in",dpi = 300)
    

```


```{r plot_gar_factor_contribution}

gar_factors_df = lapply(
  names(results$qreg_result),function(temp_name){
    
    data_mat = results$reg_df %>%
      select(names(current_partition)) %>%
      as.matrix()
    
    coef_vec = coefficients(results$qreg_result[[temp_name]])[-1,1]
    
    gar_factors_df =  t(t(data_mat) * coef_vec)
    
    gar_factors_df = cbind(date = results$reg_df$date,
                           as.data.frame(gar_factors_df)) %>% 
      mutate(Horizon = temp_name)
    
    return(gar_factors_df)
 
                        })

names(gar_factors_df) = names(results$qreg_result)

gar_factors_df = lapply(gar_factors_df,function(temp_df){
  
  temp_df = temp_df %>% 
    rename(Macro = Dom_Macro) %>% 
    rename(`Fin. Cycle` = FinCycle) %>% 
    rename(`Fin. Conditions` = Dom_FCI)
  
  return(temp_df)
  
})

gar_factor_plot_list = lapply(names(gar_factors_df), function(temp_name){
  
  plot_df = gar_factors_df[[temp_name]] %>% 
  gather(key = Partition, value = GaR, -date, -Horizon)

temp_plot = ggplot() + 
  geom_col(data = plot_df, mapping = aes(x = date, y = GaR,
                                         fill = Partition),
           position = "stack", size = 5) +
  geom_line(data = plot_df %>%
              group_by(date) %>%
              summarise(Total = sum(GaR),.groups = "drop") %>%
              ungroup(),mapping =  aes(x = date, y = Total)) +
  scale_fill_viridis_d(option = "plasma") +
  labs(title = paste("Growth at risk partition decomposition",
                     "\n(at", temp_name, "Horizon)"),
       x = "", y = "") + 
  theme_bw() + 
  theme(legend.position = "bottom",
        legend.title = element_blank(),
        plot.title = element_text(hjust = 0.5))

  return(temp_plot)

})

names(gar_factor_plot_list) = names(gar_factors_df)


sapply(names(gar_factor_plot_list),
       function(temp_name){
  
  ggsave(filename =
           paste0(file.path(Sys.getenv("USERPROFILE"),
                            "Desktop",fsep="\\"),
                  "\\GaR_factor",temp_name,
                  "_Horizon.png"),
         plot = gar_factor_plot_list[[temp_name]],
       device = "png",width = 5,height = 4.5,
       units = "in",dpi = 300)
  
         
         
       })




```


```{r prediction_comparison}

temp = forecast_model_fit[c("gar_macro_r2","gar_staff_r2")] %>% 
  reduce(full_join,
         by = c("Horizon","Quantile"),
         suffix = c("_macro","_staff")) %>% 
  rename_all(~str_remove_all(.,"_r2_score")) %>% 
  select(-gar_staff) %>% 
  rename_at(vars(gar_macro),.funs = ~"gar") %>% 
  pivot_longer(cols = c(-Horizon, -Quantile),
               names_to = "model",
               values_to = "score")
  
good_fit_plot = ggplot(temp, aes(x = Quantile, y = score, fill = model)) + 
  geom_col(position = 'dodge', width = 0.5) + 
  scale_fill_viridis_d(labels = c("GaR", "Macro only", "Staff")) + 
  labs(y = expression("quantile"~R^2), title = "Forecast accuracy") + 
  facet_wrap(~Horizon,ncol = 1) + 
  theme_bw() + 
  theme(legend.position = "bottom",
        legend.title = element_blank(),
        plot.title = element_text(hjust = 0.5))


ggsave(filename =
           paste0(file.path(Sys.getenv("USERPROFILE"),
                            "Desktop",fsep="\\"),
                  "\\good_fit_plot.png"),
         plot = good_fit_plot,
       device = "png",width = 5,height = 4.5,
       units = "in",dpi = 300)

```


```{r summary_stat}

summary_table = stargazer(df %>% 
                select(-date) %>% 
                select(names(df)[names(df) %in% unlist(current_partition)]),
              summary = TRUE, header = FALSE,type = "text")


write.csv(summary_table, paste0(file.path(Sys.getenv("USERPROFILE"),
                            "Desktop",fsep="\\"),
                  "\\summary_table.csv"))

```


```{r events_plot}

recessions = read.csv(paste0(
  file.path(Sys.getenv("USERPROFILE"),fsep="\\"),
  "\\OneDrive - Bank Of Israel\\",
  "Data\\BoI\\GaR_Data","\\recessions.csv")) %>% 
  mutate(across(c(Start, End), ~as.yearqtr(.)))

events = read.csv(paste0(
  file.path(Sys.getenv("USERPROFILE"),fsep="\\"),
  "\\OneDrive - Bank Of Israel\\",
  "Data\\BoI\\GaR_Data","\\events.csv")) %>% 
  mutate(across(c(Start, End), ~as.yearqtr(.)))

predict_df =  data.frame(
  date = results$reg_df$date,
  Horizon_1 = predict(results$qreg_result$`1`,
                newdata = results$reg_df %>% 
                  rename_at(vars(-date, -starts_with("GDP")),
                            ~paste0(.,"_xreg")))[,1],
  Horizon_12 = predict(results$qreg_result$`12`,
                newdata = results$reg_df %>% 
                  rename_at(vars(-date, -starts_with("GDP")),
                            ~paste0(.,"_xreg")))[,1]) %>% 
  pivot_longer(cols = -date,
               names_to = "Horizon",
               values_to = "GaR")


events_plot = ggplot() + 
  ylim(c(-0.12,0.08)) + 
  geom_point(data = predict_df,
             mapping = aes(x = date, y = GaR, color = Horizon)) + 
  geom_line(data = predict_df,
            mapping = aes(x = date, y = GaR, color = Horizon)) + 
  geom_rect(data = recessions,
            mapping = aes(xmin = Start, xmax = End,
                          ymin = -Inf, ymax = Inf),
            fill = "lightblue", alpha = 0.5) +
  theme_bw() + 
  theme(legend.position = "bottom", legend.title = element_blank())

events_plot = events_plot + 
  geom_point(data = gar_df %>% 
             filter(date %in% events$Start),
           mapping = aes(x = date, y = GaR),
           color = "blue") + 
  geom_segment(data = gar_df %>% 
                 filter(date %in% events$Start) %>% 
                 slice(1:2),
             mapping = aes(x = date, y = c(0.0745,0.0745),
                           xend = date, yend = GaR),
             arrow = arrow(length = unit(0.1,"cm")),
             color = "blue") + 
  geom_text(data = events,
            mapping = aes(x = Start + 1, y = c(0.08,0.08,0.06),
                                          label = Event),
            color = "blue")

ggsave(filename =   paste0(file.path(Sys.getenv("USERPROFILE"),
                            "Desktop",fsep="\\"),
                  "\\events_plot.png"),
         plot =events_plot,
       device = "png",width = 5,height = 4.5,
       units = "in",dpi = 300)
```


```{r plot_quant_reg_panel}

sapply(names(results$qreg_result), function(temp_name){
  
  panel_coef_plot = plot.qreg.coeffs(results$qreg_result[temp_name],
                               print_plot = FALSE,add.significance = TRUE)
  
  panel_coef_plot = panel_coef_plot + facet_wrap(~Name,
               labeller = labeller(Name = unlist(plot_names_list)))
  
  ggsave(filename =   paste0(file.path(Sys.getenv("USERPROFILE"),
                            "Desktop",fsep="\\"),
                  "\\quantile_plot_hor_",temp_name,".png"),
         plot = panel_coef_plot,
       device = "png",width = 5,height = 4.5,
       units = "in",dpi = 300)
  
  
  
})

```

