
partitions_list  = list()

partitions_list$extensive = list(Dom_Real = list("GDP_F","Ind_Prod_Israel",
                                  "C_FP","G_NDEFIMP_FP","INV_FP",
                                  "INV_NI_FP","EXP_ND_FP","IMP_ND_FP",
                                  "STARTUP_FP"),
                  Dom_Prices = list("CPI","breakeven_inflation_1Y",
                                    "breakeven_inflation_2_3_fwd",
                                    "breakeven_inflation_5_10_fwd",
                                    "CPI_season_adj",
                                    "CPI_no_house_fruits_season_adj",
                                    "CPI_no_house_season_adj",
                                    "CPI_no_house","CPI_no_fruits"),
                  Rates = list("BOI_rate","Telbor_1Y","real_rate_1",
                               "real_rate_2_3_fwd","real_rate_5_10_fwd"),
                  External = list("CA","ILS_USD","ILS_EURO",
                                  "ILS_Yen","ILS_GBP"),
                  Global = list("VIX","Ind_Prod_advanced",
                                "Brent","Commodity_Non_Energy",
                                "gdp_us","gdp_euro","gdp_japan",
                                "gdp_uk","infl_us","infl_euro",
                                "infl_japan","infl_uk","rate_euro","rate_us",
                                "rate_uk","rate_japan","US_10","EU_10",
                                "UK_10","JPN_10", "US_5","EU_5","UK_5","JPN_5",
                                "IMP_OECD"),
                  Labor = list("Wage","EMP","Unemp_rate","Vacancies_Rate"),
                  National_Security = list("Tourists"),
                  Spread = list("Spread_CPI_corp",
                                "ILS_USD_spread_pct","Interbank_spread",
                                "Sovereigh_spread",
                                "Term_spread"),
                  Volatility = list("ILS_USD_impl_vol","TA_35_impl_vol"),
                  Returns = list("TA125_Close"),
                  Credit = list("Credit_to_non_fin_sector",
                                "Avg_House_Price_index"))

partitions_list$basic_fincycle = list(Dom_Real = list("GDP_F","Ind_Prod_Israel",
                                             "CPI","BOI_rate","real_rate_1"),
                             Global_Real = list("CA","ILS_USD","gdp_us",
                                                "gdp_euro","infl_us","infl_euro",
                                                "Ind_Prod_advanced","rate_euro","rate_us"),
                             Dom_Fin =  list("Spread_CPI_corp",
                                "ILS_USD_spread_pct","Interbank_spread",
                                "Sovereigh_spread", "Term_spread",
                                "ILS_USD_impl_vol","TA_35_impl_vol"),
                             FinCycle = list("Credit_to_non_fin_sector",
                                "Avg_House_Price_index","TA125_Close"),
                             Global_Fin = list("VIX"))


partitions_list$basic = list(Dom_Real = list("GDP_F","Ind_Prod_Israel",
                                             "CPI","BOI_rate","real_rate_1"),
                             Global_Real = list("CA","ILS_USD","gdp_us",
                                                "gdp_euro","infl_us","infl_euro",
                                                "Ind_Prod_advanced","rate_euro","rate_us"),
                             Dom_Fin =  list("Spread_CPI_corp",
                                             "ILS_USD_spread_pct","Interbank_spread",
                                             "Sovereigh_spread", "Term_spread",
                                             "ILS_USD_impl_vol","TA_35_impl_vol"))


partitions_list$OZMG = list(Dom_Macro = list("GDP_F","Ind_Prod_Israel"),
                            Global = list("gdp_us","gdp_euro","infl_us","infl_euro",
                                          "Ind_Prod_advanced","rate_euro","rate_us","VIX"),
                            Dom_FCI =  list("Spread_CPI_corp",
                                            "ILS_USD_spread_pct","Interbank_spread",
                                            "Sovereigh_spread", "Term_spread",
                                            "ILS_USD_impl_vol","TA_35_impl_vol"),
                            FinCycle = list("Credit_to_non_fin_sector",
                                            "Avg_House_Price_index","TA125_Close"))

partitions_list$OZMG_no_fincycle = list(Dom_Macro = list("GDP_F","Ind_Prod_Israel"),
                            Global = list("gdp_us","gdp_euro","infl_us","infl_euro",
                                          "Ind_Prod_advanced","rate_euro","rate_us","VIX"),
                            Dom_FCI =  list("Spread_CPI_corp",
                                            "ILS_USD_spread_pct","Interbank_spread",
                                            "Sovereigh_spread", "Term_spread",
                                            "ILS_USD_impl_vol","TA_35_impl_vol"))
