

```{r short_partitons}

baseline_partitions = list(DomReal = c(partitions[c("Dom_Real",
                                                   "Dom_Prices",
                                                   "Labor")] %>% 
                                         reduce(unlist)),
                           DomFin = c(partitions[c("Fin_Cycle",
                                                  "Rates","Risk")] %>% 
                                         reduce(unlist)),
                           GlobalReal = c(partitions$Global %>% 
                                           str_subset(pattern = "gdp|Ind|IMP")),
                           GlobalFin = c(partitions$Global %>% 
                                           str_subset(pattern = "gdp|Ind|IMP",
                                                      negate = TRUE)))



minimal_partition = list(Dom_Real = list("GDP_F","Ind_Prod_Israel"),
                         Dom_Prices = list("CPI","breakeven_inflation_1Y",
                                    "breakeven_inflation_2_3_fwd",
                                    "breakeven_inflation_5_10_fwd"),
                         Rates = list("BOI_rate","Spread_CPI_corp",
                                      "ILS_USD_spread_pct","Interbank_spread",
                                      "Sovereigh_spread","Term_spread"),
                         External = list("CA","ILS_USD","ILS_EURO"),
                         Global = list("VIX","Ind_Prod_advanced",
                                "Brent","Commodity_Non_Energy",
                                "gdp_us","gdp_euro","gdp_japan",
                                "gdp_uk","infl_us","infl_euro",
                                "infl_japan","infl_uk","rate_euro","rate_us",
                                "rate_uk","rate_japan","US_10","EU_10",
                                "UK_10","JPN_10", "US_5","EU_5","UK_5","JPN_5",
                                "IMP_OECD"),
                         Volatility = list("ILS_USD_impl_vol","TA_35_impl_vol"),
                         Credit = list("Credit_to_non_fin_sector",
                                       "Avg_House_Price_index"))


partitions_list = list(baseline_partitions = baseline_partitions,
                       minimal_partition = minimal_partition)

rm(list = names(partitions_list))

```


```{r GaR_analysis}

data_specs_gar = lapply(data_list, function(temp_data){
  
  temp_gar_obj = run.GaR.analysis(partitions_list = partitions,
                               vars_df = temp_data,
                               horizon_list = parameters_list$horizon_list,
                               quantile_vec = parameters_list$quantile_vec)
  
  return(temp_gar_obj)
  
  
})


partitons_specs_gar = run.GaR.analysis(partitions_list = baseline_partitions,
                                   vars_df = data_list$interpolated_df,
                                   horizon_list = parameters_list$horizon_list,
                                   quantile_vec = parameters_list$quantile_vec)

```


```{r Forecast}

data_specs_gar_forecast = lapply(data_specs_gar, function(temp_gar_obj){
  
  temp_forecast = get.gar.forecast(gar_obj = temp_gar_obj,
                        win_len = 30,
                        quantile_vec = parameters_list$quantile_vec,
                        out_of_sample_step = 1)
  
  return(temp_forecast)
  
})

partitons_specs_forecast = get.gar.forecast(
  gar_obj = partitons_specs_gar,
  win_len = 30,
  quantile_vec = parameters_list$quantile_vec,
  out_of_sample_step = 1)


forecast_list = c(data_specs_gar_forecast,
                  baseline_partition = list(partitons_specs_forecast))

```


```{r error_df}


error_df =lapply(names(forecast_list), function(temp_name){
  
  temp_df = forecast_list[[temp_name]]
  
  temp_df = temp_df %>% 
    filter(!is.na(Error)) %>% 
    mutate(Category = temp_name)
  
  return(temp_df)
    
  
  
}) %>% 
  bind_rows() %>% 
  mutate(Date = as.yearqtr(Date))

# data_specs_gar_forecast_error = lapply(names(data_specs_gar_forecast),
#                   function(temp_name){
#                     
#                   temp_error_df = forecast_obj_list[[temp_name]] %>% 
#                     filter(!is.na(GaR_actual)) %>% 
#                     filter(Quantile == "0.50") %>% 
#                     group_by(Horizon, Forecast_Status) %>% 
#                     mutate(Error = GaR_actual - GaR_forecast) %>% 
#                     summarise(RMSE = mean(Error ^ 2), MAD = mean(abs(Error))) %>%
#                     mutate(Type = temp_name)
#                     
#                     
#                     
#                     
#                   }) %>% 
#   bind_rows()

```


```{r}

ggplot(error_df %>% 
         group_by(Category,Horizon,Forecast_Status) %>% 
         summarise(MAD = mean(abs(Error))) %>% 
         select(Horizon, MAD, Category,Forecast_Status),
       aes(x = Horizon, y = MAD, fill = Category)) + 
  geom_bar(stat = "identity", position = "dodge", width = 0.3) + 
  scale_fill_brewer(palette="Set1") + 
  facet_wrap(~Forecast_Status) + 
  theme_bw() + 
  theme(legend.position = "bottom")

```

