---
output:
  rmarkdown::pdf_document:
    latex_engine: xelatex
    includes:
            in_header: C:\\Users\\Misha\\Documents\GaR\\GaR-preamble.tex

vignette: >
  %\VignetteIndexEntry{GaR analysis}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF_8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE, echo = FALSE, message = FALSE,warning = FALSE,
  comment = "#>"
)
```


```{r init_setup}

devtools::load_all()

library(GaRPackg)
```


```{r load_libraries}

library(xts)

library(tidyselect)

library(ggplot2)

library(cowplot)

library(mFilter)

library(quantreg)

library(rlang)

```


```{r Set_parameters}

partitions = list(domestic_macro = list('real_gdp_yoy',
                                        'industrial_prod_yoy','pmi',
                                        "cyclical_composite_yoy"),
                  domestic_fci = list('term_spread', 'corporate_spread',
                                      'interbank_spread','sovereign_spread',
                                      'securities_ba_spread',
                                      'equity_returns_qoq', 'policy_rate',
                                      'cpi_inflation', 
                                      'implied_yield_cpi_bond_yoy',
                                      'inflation_expectations',
                                      'fx_returns_qoq', 'fx_ba_spread',
                                      'equity_implied_vol'),
                  leverage = list('private_credit_gdp', 'loan_deposits_ratio',
                                  'tier1_rwa', 'npl_ratio', 'share_fx_loans',
                                  'nfc_debt_equity',
                                  'derivatives_assets_capital',
                                  'liquid_assets_st_liabilities',
                                  'net_fx_positions_capital'),
                  external = list('ca_gdp','reer_yoy', 'trade_gdp',
                                  'dom_investment_gdp'),
                  world_macro = list('world_real_gdp_yoy',
                                     'world_indus_prod_yoy'),
                  world_fci = list('vix','nasdaq_returns_qoq', 'nasdaq_vol',
                                   'oil_future_qoq','us_reer_eme_yoy'))


pls_target_list = list(domestic_macro = list("real_gdp_yoy", "pmi"),
                   domestic_fci = list("term_spread", "corporate_spread"),
                   leverage = list("private_credit_gdp"),
                   world_macro = list("world_real_gdp_yoy"),
                   world_fci = list("vix", "nasdaq_returns_qoq"))


horizon_list = c(1,4,8,12)

qregs_results = list()

partitions_df = list()

```


```{r Import_data}

df = read.csv(paste0("C:\\Users\\Misha\\Documents\\GaR Python\\Israel",
                     " GaR\\Data\\Final\\final_data_israel.csv"),
              stringsAsFactors = FALSE) %>% 
  mutate(date = as.Date(date)) %>% 
  filter(date >= as.Date("1996-01-01") & date <= as.Date("2019-06-01"))

```

<!-- Calculate partitons -->

```{r get_chained_pca_partitons}

df_interpolated = df %>% 
  mutate_at(vars(-date), interpolate)

partitions_df$chained = lapply(partitions,function(temp_part){
    df_interpolated %>% 
    select(unlist(temp_part), date) %>% 
    chain_index(sign_align_params = list(
      df_interpolated[,c("date",temp_part[[1]])]))}) %>%
  reduce(full_join, by = "Date") %>% 
  setNames(c("Date", names(partitions)))


partitions_df$chained = left_join(df %>% 
                            select(date, real_gdp_nis_y),
                          partitions_df$chained, by = c("date" = "Date"))
                

```


```{r get_complete_pca_partitons, eval=FALSE}

partitions_df$complete = lapply(partitions,function(temp_part){
    df_interpolated %>% 
    select(unlist(temp_part), date) %>% 
    filter(complete.cases(.)) %>% 
    pca_reduction(sign_align_params = list(
      df_interpolated[,c("date",temp_part[[1]])]))}) %>%
  reduce(full_join, by = "Date") %>% 
  setNames(c("Date", names(partitions)))


partitions_df$complete = left_join(df %>% 
                            select(date, real_gdp_nis_y),
                          partitions_df$complete, by = c("date" = "Date"))
                

```


<!-- Run quantile regressions -->

```{r get_chained_quantile_regressions}

qregs_results$chained = lapply(horizon_list, function(temp_horizon){

  reg_df = make.quant.reg.df(partitions_df = partitions_df$chained %>% 
                             select(-real_gdp_nis_y),
                           dep_var_df = partitions_df$chained %>% 
                             select(date, real_gdp_nis_y) %>% 
                             rename("GDP_growth" = real_gdp_nis_y),
                           horizon = temp_horizon)
  
  
  qreg_list = rq(formula = formula("GDP_growth~."),
               tau = c(0.05,0.25,0.5,0.75,0.95),
               data = as.data.frame(scale(reg_df %>% 
                                            select(-date))))  
  
  return(qreg_list)
  
  
})

names(qregs_results$chained) = horizon_list


```


```{r get_complete_quantile_regressions, eval=FALSE}

qregs_results$complete = lapply(horizon_list, function(temp_horizon){

  reg_df = make.quant.reg.df(partitions_df = partitions_df$complete %>% 
                             select(-real_gdp_nis_y),
                           dep_var_df = partitions_df$complete %>% 
                             select(date, real_gdp_nis_y) %>% 
                             rename("GDP_growth" = real_gdp_nis_y),
                           horizon = temp_horizon)
  
  
  qreg_list = rq(formula = formula("GDP_growth~."),
               tau = c(0.05,0.25,0.5,0.75,0.95),
               data = as.data.frame(scale(reg_df %>% 
                                            select(-date))))  
  
  return(qreg_list)
  
  
})

names(qregs_results$complete) = horizon_list


```


<!-- Plot results -->

\section{Chained quantile regressions}

```{r plot_chained_quantile_coeffs}

invisible(sapply(names(qregs_results$chained), function(temp_horizon){
  
  coef_table = extract.qreg.coeff.table(qregs_results$chained[[temp_horizon]])
  
  plot = ggplot(coef_table %>% 
  mutate(Name = gsub(pattern = "estic",replacement = "",
                     x = Name, fixed = TRUE)) %>%
  mutate(Name = factor(Name,
                       levels = c("dom_macro","dom_fci",
                                  "leverage","external",
                                  "world_macro","world_fci",
                                  "Intercept"))) %>% 
    filter(!Name == "Intercept"),
       aes(x = Tau, y = Coeff, fill = Significant)) + 
  geom_bar(stat = "identity", width = 0.2, position = "dodge") + 
  geom_hline(yintercept = 0, linetype = "dashed") + 
  guides(fill = guide_legend(override.aes = list(shape = 22))) + 
  facet_wrap(~Name) +
  labs(x = "Quantile", y = "",
       title = paste0("Quantile regression coefficients \n (",
                                     temp_horizon, " quarters ahead)")) + 
  theme_bw() + 
  theme(plot.title = element_text(hjust = 0.4),
        # axis.text.y = element_blank(), axis.ticks.y = element_blank(),
        legend.position = "bottom")
  
  print(plot)
  
  
}))





  
  

```


```{r plot_factor_contribution}

coef_mat = qregs_results$chained$`1`$coefficients %>% 
  as.data.frame(.) %>% 
  setNames(gsub("tau= ","",colnames(.))) %>% 
  mutate(Name = gsub("[()]","",rownames(.)))


ggplot(coef_mat %>% 
         select(Name, `0.50`) %>% 
         filter(!Name == "Intercept"), aes(x = Name, y = `0.50`)) + 
  geom_bar(stat = "identity") + 
  theme_bw()


```



\section{Complete quantile regressions}


```{r plot_complete_quantile_coeffs, eval=FALSE}

invisible(sapply(names(qregs_results$complete), function(temp_horizon){
  
  coef_table = extract.qreg.coeff.table(qregs_results$complete[[temp_horizon]])
  
  plot = ggplot(coef_table %>% 
  mutate(Name = gsub(pattern = "estic",replacement = "",
                     x = Name, fixed = TRUE)) %>%
  mutate(Name = factor(Name,
                       levels = c("dom_macro","dom_fci",
                                  "leverage","external",
                                  "world_macro","world_fci",
                                  "Intercept"))) %>% 
    filter(!Name == "Intercept"),
       aes(x = Tau, y = Coeff, fill = Significant)) + 
  geom_bar(stat = "identity", width = 0.2, position = "dodge") + 
  geom_hline(yintercept = 0, linetype = "dashed") + 
  facet_wrap(~Name,scales = "free_y") +
  labs(x = "", y = "", title = paste("Quantile regression coefficients",
                                     temp_horizon, "ahead")) + 
  theme_bw() + 
  theme(plot.title = element_text(hjust = 0.4),
        axis.text.x = element_text(angle = 90),
        # axis.text.y = element_blank(), axis.ticks.y = element_blank(),
        legend.position = "bottom")
  
  print(plot)
  
  
}))





  
  

```


```{r get_timeseries_gar, eval=FALSE}

reg_df = make.quant.reg.df(chained_partitions_df = chained_partitions_df %>% 
                             select(-real_gdp_nis_y),
                           dep_var_df = chained_partitions_df %>% 
                             select(date, real_gdp_nis_y) %>% 
                             rename("GDP_growth" = real_gdp_nis_y),
                           horizon = 1)

reg_df = xts(x = reg_df %>% 
               select(-date),order.by = as.Date(reg_df$date))

temp = rollapply(reg_df, width = 31,FUN =  function(temp_reg_df){
  
  reg_df = temp_reg_df[1:10,]

  quant_reg = rq(formula = formula("GDP_growth~."),
               tau = 0.05,
               data = as.data.frame(coredata(reg_df)))
  
  return(predict(object = quant_reg,newdata = temp_reg_df[11,]))
  
  
},
by.column = FALSE)



```


```{r plot_time_series_gar, eval=FALSE}

ggplot(temp %>% 
         as.data.frame() %>% 
         mutate(Date = rownames(.)) %>% 
         setNames(c("GaR","Date")) %>% 
                    filter(complete.cases(.)),
       aes(x = Date, y = GaR, group = 1)) + 
  geom_line() +
  labs(x = "",y = "",
       title = "Timeseries of predicted GDP growth \n (5th quantile)") + 
  theme_bw() + 
  theme(axis.text.x = element_text(angle = 90),
        plot.title = element_text(hjust = 0.5))


```


