
```{r get_chained_quantile_regressions}

qregs_results$chained = lapply(horizon_list, function(temp_horizon){

  reg_df = make.quant.reg.df(partitions_df = partitions_df$chained %>% 
                             select(-real_gdp_nis_y),
                           dep_var_df = partitions_df$chained %>% 
                             select(date, real_gdp_nis_y) %>% 
                             rename("GDP_growth" = real_gdp_nis_y),
                           horizon = temp_horizon)
  
  
  qreg_list = rq(formula = formula("GDP_growth~."),
               tau = tau_vec,
               data = as.data.frame(scale(reg_df %>% 
                                            select(-date))))  
  
  
  
  return(qreg_list)
  
  
})

names(qregs_results$chained) = horizon_list


```


```{r get_complete_quantile_regressions, eval=FALSE}

qregs_results$complete = lapply(horizon_list, function(temp_horizon){

  reg_df = make.quant.reg.df(partitions_df = partitions_df$complete %>% 
                             select(-real_gdp_nis_y),
                           dep_var_df = partitions_df$complete %>% 
                             select(date, real_gdp_nis_y) %>% 
                             rename("GDP_growth" = real_gdp_nis_y),
                           horizon = temp_horizon)
  
  
  qreg_list = rq(formula = formula("GDP_growth~."),
               tau = c(0.05,0.25,0.5,0.75,0.95),
               data = as.data.frame(scale(reg_df %>% 
                                            select(-date))))  
  
  return(qreg_list)
  
  
})

names(qregs_results$complete) = horizon_list


```

