

```{r get_chained_pca_partitons}

df_interpolated = df %>% 
  select_if(list(~!all(is.na(.)))) %>% 
  mutate_at(vars(-date), interpolate)

partitions_df$chained = lapply(partitions,function(temp_part){
    df_interpolated %>% 
    select(unlist(temp_part)[unlist(temp_part) %in% names(.)], date) %>% 
    chain_index(sign_align_params = list(
      df_interpolated[,c("date",temp_part[[1]])]))}) %>%
  reduce(full_join, by = "Date") %>% 
  setNames(c("Date", names(partitions)))


partitions_df$chained = left_join(df %>% 
                            select(date, real_gdp_nis_y),
                          partitions_df$chained, by = c("date" = "Date"))
                

```


```{r get_complete_pca_partitons, eval=FALSE}

partitions_df$complete = lapply(partitions,function(temp_part){
    df_interpolated %>% 
    select(unlist(temp_part), date) %>% 
    filter(complete.cases(.)) %>% 
    pca_reduction(sign_align_params = list(
      df_interpolated[,c("date",temp_part[[1]])]))}) %>%
  reduce(full_join, by = "Date") %>% 
  setNames(c("Date", names(partitions)))


partitions_df$complete = left_join(df %>% 
                            select(date, real_gdp_nis_y),
                          partitions_df$complete, by = c("date" = "Date"))
                

```

