

```{r load_library}

library(corrplot)

library(devtools)

load_all()

```


```{r set_forecast_parameters}


theme_set(theme_bw())

forecast_parameters = list(
  win_len = 40,
  win_type_expanding = TRUE,
  df = df %>% filter(date < as.yearqtr("2020Q1"))
    )

forecast_benchmarks = list()

forecast_data_list = list()

forecast_model_fit = list()

models_list = list(
  One_Forecast = partitions_list$real_fin_one,
  Temp_Forecast = partitions_list$temp,
  Intercept_Forecast = NULL
  )

# models_list = list(
#   real_fin_glob_one_Forecast = partitions_list$real_fin_glob_one,
#   real_fin_glob_two_Forecast = partitions_list$real_fin_glob_two,
#   real_fin_glob_three_Forecast = partitions_list$real_fin_glob_three,
#   real_fin_one_Forecast = partitions_list$real_fin_one,
#   real_fin_two_Forecast = partitions_list$real_fin_two,
#   real_fin_three_Forecast = partitions_list$real_fin_glob_three,
#   real_fin_glob_ext_Forecast = partitions_list$real_fin_glob_extended,
#   Intercept_Forecast = NULL
#   )


```


```{r make_actual_gdp_df}

forecast_benchmarks$actual_gdp_df = forecast_parameters$df %>% 
  select(date, GDP) %>% 
  filter(complete.cases(.)) %>% 
  rename(GDP_actual = GDP) %>% 
  mutate(Forecast_Period = paste(date - 1, date, sep = "-")) %>% 
  select(-date) %>% 
  select(Forecast_Period, GDP_actual)





```


```{r reg_dfs, eval=FALSE}


temp_xreg_list = map(
  models_list,
  reduce_data_dimension,
  vars_df = df
  )


extract.comp.from.xreg.list = function(comp_name, xreg_list){
  
  comp_list = map2(
  names(xreg_list),
  xreg_list,
  function(temp_name, temp_df){
    
    temp_df = temp_df[[1]]
  
  if(comp_name %in% names(temp_df)){
    
    return(temp_df %>% 
      select("date", all_of(comp_name)) %>% 
      rename(!!sym(temp_name) := !!sym(comp_name)))
    
    
  }
  
  
}
)
  
  comp_list = comp_list[!sapply(comp_list, is.null)]
  
  comp_list = comp_list %>% 
    reduce(inner_join, by = "Date") %>% 
    select(-Date) %>% 
    filter(complete.cases(.))
  
  return(comp_list)
  
}

corr_df_list = map(
  list(
    Dom_Macro = "Dom_Macro",
    FinCycle = "FinCycle",
    Global = "Global"),
  extract.comp.from.xreg.list,
  xreg_list = temp_xreg_list)


for(temp_name in names(corr_df_list)){
  
  corrplot(cor(corr_df_list[[temp_name]]),
         type = "upper",
         diag = FALSE,
         tl.srt = 0,
         tl.cex = 0.5,
         mar = c(1,5,1,1),
         method = "number",
         title = temp_name)
}


```


```{r GaR_Forecast_pca}

forecast_data_list = map(names(models_list),
  function(temp_name){
    
    temp_df = get_gar_forecast(
      partitions_list = models_list[[temp_name]],
      vars_df = forecast_parameters$df,
      target_var_name = "GDP",
      horizon_list = parameters_list$horizon_list,
      quantile_vec = parameters_list$quantile_vec,
      pca.align.list = NULL,
      win_len = forecast_parameters$win_len,
      win_type_expanding = forecast_parameters$win_type_expanding,
      method = "inner_join_pca"
      ) %>% 
      rename(!!sym(temp_name) := GaR_forecast)
    
    
    return(temp_df)

  }
  
  )

names(forecast_data_list) = names(models_list)

```


```{r GaR_Forecast_pls, eval=FALSE}

forecast_data_list = map(names(models_list),
  function(temp_name){
    
    temp_df = get_gar_forecast(
      partitions_list = models_list[[temp_name]],
      vars_df = forecast_parameters$df,
      target_var_name = "GDP",
      horizon_list = parameters_list$horizon_list,
      quantile_vec = parameters_list$quantile_vec,
      method = "pls",
      win_len = forecast_parameters$win_len,
      win_type_expanding = forecast_parameters$win_type_expanding
      ) %>% 
      rename(!!sym(temp_name) := GaR_forecast)
    

    return(temp_df)
    
    

  }
  
  )

names(forecast_data_list) = names(models_list)

```



```{r plot_forecast, eval=FALSE}

forecast_data_list %>% 
  reduce(inner_join) %>% 
  pivot_longer(-c(Quantile,Horizon,Date)) %>% 
  ggplot(aes(x = Date, y = value, color = name)) + 
  geom_line() + 
  facet_grid(rows = vars(Quantile), cols = vars(Horizon)) + 
  theme(legend.position = "bottom", legend.title = element_blank())

```


<!-- Staff forecast -->


```{r, make_staff_forecast}

staff_forecast_conversion_table = read_csv(
  paste0(file.path(Sys.getenv("USERPROFILE"), fsep = "\\"),
         "\\OneDrive - Bank Of Israel\\Data\\BoI\\GaR_Data\\",
         "Staff_forecast_conversion_table.csv"))

staff_forecast_conversion_table = staff_forecast_conversion_table %>% 
  filter(Type == "YoY") %>% 
  select(-Type) %>% 
  mutate(Horizon = as_factor(Horizon,)) %>% 
  pivot_longer(cols = c(-Horizon),
               names_to = "Quantile",
               values_to = "Conversion_Coeff") %>% 
  mutate(Conversion_Coeff = Conversion_Coeff * 0.01)

staff_forecast_conversion_table = full_join(
  staff_forecast_conversion_table,
  select(raw_df, Date), by = character())
  

staff_forecast_df_h1 = raw_df %>% 
  select(Date, staff_1Q) %>% 
  rename_all(.funs = list(~str_remove(.,"staff_"))) %>% 
  gather(key = Quarter,value = Forecast, - Date) %>% 
  filter(complete.cases(.)) %>% 
  left_join(.,raw_df %>% 
              select(Date, GDP) %>% 
              mutate(GDP = GDP / lag(GDP,3) - 1)) %>% 
  mutate(Staff_Forecast = Forecast * 0.25 * 0.01 + GDP) %>% 
  select(Date,Staff_Forecast) %>% 
  mutate(Forecast_Period = paste(Date - 0.75,Date + 0.25,
                                 sep = "-")) %>% 
  mutate(Horizon = "1")


staff_forecast_df_h4 = raw_df %>%
  select(Date, staff_1Q, staff_2Q, staff_3Q, staff_4Q) %>%
  rename_all(.funs = list(~str_remove(.,"staff_"))) %>%
  gather(key = Quarter,value = Forecast, - Date) %>%
  group_by(Date) %>%
  summarise(Staff_Forecast = mean(Forecast) * 0.01) %>%
  ungroup() %>%
  filter(complete.cases(.)) %>%
  mutate(Forecast_Period = paste(Date,(Date + 1),
                                 sep = "-")) %>%
  mutate(Horizon = "4")



staff_forecast_df_h8 = raw_df %>% 
  select(Date, staff_5Q, staff_6Q, staff_7Q, staff_8Q) %>% 
  rename_all(.funs = list(~str_remove(.,"staff_"))) %>% 
  gather(key = Quarter,value = Forecast, - Date) %>% 
  group_by(Date) %>% 
  summarise(Staff_Forecast = mean(Forecast) * 0.01) %>% 
  ungroup() %>% 
  filter(complete.cases(.)) %>% 
  mutate(Forecast_Period = paste((Date + 1),(Date + 2),
                                 sep = "-")) %>% 
  mutate(Horizon = "8")

forecast_benchmarks$staff_forecast = list(
  staff_forecast_df_h1,
  staff_forecast_df_h4,
  staff_forecast_df_h8) %>% 
  bind_rows() %>% 
  mutate(Date = as.yearqtr(Date)) %>% 
  inner_join(., staff_forecast_conversion_table,
             by = c("Date","Horizon")) %>% 
  mutate(Staff_Forecast = Staff_Forecast + Conversion_Coeff) %>% 
  mutate(Quantile = str_replace_all(Quantile,"0.5","0.50")) %>% 
  select(-Conversion_Coeff) %>% 
  select(Date, Horizon, Quantile, Forecast_Period, Staff_Forecast)

rm(list = str_subset(ls(),"staff"))



```


```{r staff_r2}

temp_bench = forecast_benchmarks %>% 
  reduce(left_join,
         by = "Forecast_Period")

temp_forecast = forecast_data_list %>% 
  reduce(inner_join,by = c("Date","Quantile","Horizon")) %>% 
  mutate(Forecast_Period = paste(
    Date + as.numeric(Horizon) * 0.25 - 1,
    Date + as.numeric(Horizon) * 0.25,
    sep = "-")) %>% 
  select(-Date)
  
forecast_model_fit$staff_r2 = inner_join(
  temp_bench,
  temp_forecast,
  by = c("Forecast_Period", "Horizon", "Quantile")) %>% 
  select(-Forecast_Period) %>% 
  group_by(Horizon, Quantile) %>% 
  summarise(across(contains("Forecast") & !"Intercept_Forecast",
                   ~quantile.r2.score(
                     realized_values = GDP_actual,
                     forecast_values = .,
                     quantile = as.numeric(Quantile[1]),
                     benchmark_values = Intercept_Forecast)),
            .groups = "drop")


rm(list = str_subset(ls(), "temp"))

```


```{r r_2}

forecast_model_fit$r2 = forecast_data_list %>% 
  reduce(inner_join,by = c("Quantile", "Horizon", "Date")) %>% 
  mutate(Forecast_Period = paste(
    Date + as.numeric(Horizon) * 0.25 - 1,
    Date + as.numeric(Horizon) * 0.25,
    sep = "-")) %>% 
  inner_join(forecast_benchmarks$actual_gdp_df,
             by = "Forecast_Period") %>% 
  select(-Forecast_Period) %>% 
  group_by(Quantile, Horizon) %>% 
  summarise(across(
    contains("Forecast") & !"Intercept_Forecast",
    ~quantile.r2.score(
      realized_values = GDP_actual,
      forecast_values = .,
      quantile = as.numeric(Quantile[1]),
      benchmark_values = Intercept_Forecast)))



```


```{r r_pit}

forecast_model_fit$pit = map2(
  names(forecast_data_list),forecast_data_list,
  function(temp_name, temp_df){
    pit_df = temp_df %>% 
      mutate(Forecast_Period = paste(
        Date + as.numeric(Horizon) * 0.25 - 1,
        Date + as.numeric(Horizon) * 0.25,
        sep = "-")) %>% 
      inner_join(forecast_benchmarks$actual_gdp_df,
                 by = "Forecast_Period") %>% 
      select(-Forecast_Period) %>% 
      rename(actual_values = GDP_actual) %>% 
      rename(predicted_values = !!sym(temp_name)) %>% 
      quantile_pit_score() %>% 
      mutate(model = temp_name)
    
    return(pit_df)
    
    
  }) %>% 
  bind_rows()
  
  



```


```{r plot_r_2}

forecast_model_fit$r2 %>% 
  pivot_longer(cols = -c("Horizon","Quantile")) %>% 
  ggplot(aes(x = Quantile, y = value, fill = name)) + 
  geom_col(position = "dodge") + 
  scale_fill_viridis_d() + 
  facet_wrap(~Horizon, scales = "free") + 
  theme(legend.position = "bottom", legend.title = element_blank())

```



```{r plot_staff_r_2}

forecast_model_fit$staff_r2 %>% 
  pivot_longer(cols = -c("Horizon","Quantile")) %>% 
  ggplot(aes(x = Quantile, y = value, fill = name)) + 
  geom_col(position = "dodge") + 
  scale_fill_viridis_d() + 
  facet_wrap(~Horizon, scales = "free") + 
  theme(legend.position = "bottom", legend.title = element_blank())

```




```{r plot_pit}

forecast_model_fit$pit %>% 
  ggplot(aes(x = Quantile, y = pit, color = model, group = model)) + 
  geom_line() + 
  scale_color_viridis_d() + 
  geom_line(aes(x = Quantile,y = as.numeric(Quantile)),
            linetype = "dashed", color = "black") + 
  xlab(NULL) + ylab(NULL) + 
  facet_wrap(~Horizon, scales = "free") + 
  theme_bw() + 
  theme(legend.position = "bottom", legend.title = element_blank())

```



```{r plot_actual}

forecast_benchmarks$actual_gdp_df %>% 
  separate(col = Forecast_Period, into = c("start","end"),
           sep = "-") %>% 
  mutate(start = as.yearqtr(start)) %>% 
  ggplot(aes(x = start, y = GDP_actual)) + 
  scale_y_continuous(labels = scales::percent_format()) + 
  geom_line()

```


```{r plot_residuals}

temp_df %>% 
  mutate(across(c("GaR_forecast","Intercept_Forecast"),
                ~ GDP_actual - .)) %>% 
  select(-GDP_actual) %>% 
  pivot_longer(cols = -Date) %>% 
  ggplot(aes(x = Date, y = value, color = name)) +
  geom_line() + 
  geom_hline(yintercept = 0, color = "black", linetype = "dashed") + 
  labs(x = "", y = "", title = "Prediction errors") + 
  scale_y_continuous(labels = scales::percent_format()) + 
  theme(legend.position = "bottom", legend.title = element_blank())


```


```{r temp, eval=FALSE}

pc1 = reduce_data_dimension(df,partitions_list$real_fin_glob_two,
                            return_objects_list = TRUE)

pc2 = reduce_data_dimension(df,partitions_list$real_fin_glob_three,
                            return_objects_list = TRUE)

```

