---
title: "Inflation Risks in Israel"
author: "Michael Gurkov and Osnat Zohar"
institute: "Bank of Israel \\newline Research Department \\newline \\newline Any views expressed in the Discussion Paper are those of the authors and do not necessarily reflect those of the Bank of Israel"
date: "27 July, 2021"
classoption: t
output:
  beamer_presentation:
    includes:
      in_header: !expr here::here('vignettes/GaR-PresentationPreamble.tex')
    latex_engine: xelatex
    slide_level: 2
# bibliography: "GaR.bib"
---


```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE, echo = FALSE, message = FALSE,
  warning = FALSE, comment = "#>"

)
```


```{r init_setup}

devtools::load_all()

library(ggcorrplot)

library(mFilter)

library(tidyverse)

library(lubridate)

library(slider)

library(cowplot)

library(broom)

library(gghighlight)

library(glue)

setwd(paste0(
  file.path(Sys.getenv("USERPROFILE"),fsep = "\\"),
  "\\Documents\\GaRPackg\\vignettes"))


```



```{r set_params}

partitions_list_infl = list(
  inflation = c("cpi_yoy"),
  expect_5Y5Y = c("beir5y5y"),
  exchange_rate = c("nis_usd_percent_change"),
  oil_p = c("brent_usd_percent_change"),
  output_gap = c("meshulav_gap")
)



horizon_list=c(1,12)

quantile_vec=c(0.10,0.25,0.5,0.75,0.90)




```

```{r load_data}

raw_df = import_from_fame_template(
  paste0(
    file.path(Sys.getenv("USERPROFILE")),
    "\\OneDrive - Bank Of Israel\\Data\\BoI\\IaR_data\\data_Inflation_at_Risk_monthly.csv"
  ),data_frequency = "monthly"
)

x_proc_infl = raw_df %>% 
  mutate(rel_tradables = cpi_tradables / cpi_nontradables_excl_fv_hous) %>%
  preprocess_df(
    vars_to_yoy = c(
      "cpi",
      "cpi_excl_fv",
      "cpi_excl_fv_hous",
      "cpi_excl_hous",
      "rel_tradables",
      "cpi_oecd",
      "cpi_us",
      "cpi_euro",
      "debt_business",
      "debt_households",
      "house_price",
      "ta125"
    ),
    vars_to_percent_changes = c("nis_usd",
                                "neer",
                                "brent_usd",
                                "brent_nis",
                                "non_energy_p"),
    convert_to_percent_units = TRUE
  ) %>%
  mutate(target = target * 100) %>% 
  mutate(cpi_orig = cpi) %>% 
  mutate(cpi = cpi_excl_fv_hous) %>% 
  mutate(cpi_lag = lag(cpi)) %>% 
  filter(year(date) >= 2004 & year(date) <= 2019)

filter_obj =  hpfilter(df$madad_meshulav,freq = 1600)

x_proc_infl = x_proc_infl %>% 
  mutate(meshulav_gap = filter_obj$cycle / filter_obj$trend[,1] * 100)


```


```{r out_of_sample_forecast}

win_length = 121

iar_forecast = get_gar_forecast(
  partitions_list = partitions_list_infl,
  vars_df = x_proc_infl,
  target_var_name = "cpi_yoy",
  horizon_list = c(4),
  quantile_vec = quantile_vec,
  pca.align.list = NULL,
  preprocess_method = "pca",
  win_len = win_length,
  win_type_expanding = TRUE
)


rm(win_len)


```

