---
title: "Test_package"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE, echo = FALSE, message = FALSE,warning = FALSE, comment = "#>"
)
```


```{r setup}

devtools::load_all()

setwd(paste0(file.path(Sys.getenv("USERPROFILE"),fsep = "\\"),
             "\\Documents\\GaRPackg\\vignettes"))


```


```{r load_libraries}

library(cowplot)

library(gghighlight)

library(tidyselect)

library(tidyverse)

library(quantreg)

library(corrplot)

library(stargazer)

library(xtable)

library(forcats)

```


```{r Set_parameters}

parameters_list = list()

parameters_list$quantile_vec = c(0.05,0.25,0.5,0.75,0.95)

parameters_list$horizon_list = list(1,8,12)

parameters_list$drop_series = c("Vacancies_Rate","Telbor_1Y","STARTUP_FP",
                "Sovereigh_spread",
                "Interbank_spread","LT_real_rate_change","Indus_prod_ind",
                "ILS_EURO",
                "breakeven_inflation_5_10_fwd")

parameters_list$vars_to_rates = c("Ind_Prod_us","Ind_Prod_euro",
                                  "Ind_Prod_Israel","GDP",
                                  "Credit","TA125_Close",
                                  "House_Price","SP500","DXY",
                                  "eurostoxx600")

parameters_list$vars_to_diff = c("BOI_rate")


```



```{r partition_basic}

partitions_list  = list()

partitions_list$basic = list(
  Dom_Macro = list("GDP", "Ind_Prod_Israel"),
  Global = list(
    "infl_us",
    "infl_euro",
    "rate_euro",
    "rate_us",
    "VIX",
    "Ind_Prod_us",
    "Ind_Prod_euro",
    "eurostoxx600",
    "SP500",
    "DXY",
    "US_term_spread"
  ),
  Dom_FCI =  list(
    "Spread_CPI_corp",
    "Sovereigh_spread",
    "Term_spread",
    "ILS_USD_impl_vol",
    "TA_35_impl_vol",
    "BOI_rate"
  ),
  FinCycle = list(
    "Credit",
    "House_Price",
    "TA125_Close"
  )
)



```


```{r Import_data}

raw_df = import.from.fame.template(
  paste0(file.path(Sys.getenv("USERPROFILE"),fsep="\\"),
         "\\OneDrive - Bank Of Israel\\",
         "Data\\BoI\\GaR_Data\\Working_data",
         "\\data_fame.csv")) %>% 
  filter(Date >= as.yearqtr("1995 Q1"))


# Use Inustrial Production without seasonal adjustment

partiton_in_env = "current_partition" %in% ls()

df = raw_df %>% 
  mutate(Ind_Prod_Israel = Ind_Prod_Israel_NSA) %>% 
  {if(partiton_in_env) select(.,Date,
                              unlist(current_partition,
                                     use.names = FALSE)) else .}

rm(partiton_in_env)

```


```{r Process_data}

# Convert to numeric

# Transform variables to rates of change YoY

df = df %>% 
  mutate_at(vars(any_of(parameters_list$vars_to_rates)),
            .funs = list(~./lag(.,4)-1))


# Transform variables to difference

df = df %>% 
  mutate(BOI_rate = c(NA,diff(BOI_rate)))





```


```{r fill_last_NA, eval=FALSE}

df = df %>% 
  mutate_at(vars(GDP,Credit),.funs = list(~fill.na.average(.)))

```


# GaR Analysis

```{r}
results = run.GaR.analysis(
  outcome_variable_name = "GDP",
  partitions_list = partitions_list$basic,
  vars_df = df,
  horizon_list = parameters_list$horizon_list,
  quantile_vec = parameters_list$quantile_vec
  )
```

